//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 02:52:48 PM CEST 
//


package no.imr.formats.nmdreference.v2;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * <p>Java class for LandingsiteElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LandingsiteElementType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.imr.no/formats/nmdreference/v2.0}StringWithAnyAttributes" minOccurs="0"/&gt;
 *         &lt;element name="code" type="{http://www.imr.no/formats/nmdreference/v2.0}StringWithAnyAttributes" minOccurs="0"/&gt;
 *         &lt;element name="region" type="{http://www.imr.no/formats/nmdreference/v2.0}StringWithAnyAttributes" minOccurs="0"/&gt;
 *         &lt;element name="placename" type="{http://www.imr.no/formats/nmdreference/v2.0}StringWithAnyAttributes" minOccurs="0"/&gt;
 *         &lt;element name="name" type="{http://www.imr.no/formats/nmdreference/v2.0}StringWithAnyAttributes" minOccurs="0"/&gt;
 *         &lt;element name="buyerid" type="{http://www.imr.no/formats/nmdreference/v2.0}StringWithAnyAttributes" minOccurs="0"/&gt;
 *         &lt;element name="locationid" type="{http://www.imr.no/formats/nmdreference/v2.0}StringWithAnyAttributes" minOccurs="0"/&gt;
 *         &lt;element name="locode" type="{http://www.imr.no/formats/nmdreference/v2.0}StringWithAnyAttributes" minOccurs="0"/&gt;
 *         &lt;element name="description" type="{http://www.imr.no/formats/nmdreference/v2.0}StringWithAnyAttributes" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.imr.no/formats/nmdreference/v2.0}GenericAttrRowGroup"/&gt;
 *       &lt;attGroup ref="{http://www.imr.no/formats/nmdreference/v2.0}DeprecatedAttrGroup"/&gt;
 *       &lt;anyAttribute/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LandingsiteElementType", propOrder = {
    "id",
    "code",
    "region",
    "placename",
    "name",
    "buyerid",
    "locationid",
    "locode",
    "description"
})
public class LandingsiteElementType {

    protected StringWithAnyAttributes id;
    protected StringWithAnyAttributes code;
    protected StringWithAnyAttributes region;
    protected StringWithAnyAttributes placename;
    protected StringWithAnyAttributes name;
    protected StringWithAnyAttributes buyerid;
    protected StringWithAnyAttributes locationid;
    protected StringWithAnyAttributes locode;
    protected StringWithAnyAttributes description;
    @XmlAttribute(name = "updatedTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updatedTime;
    @XmlAttribute(name = "updatedBy")
    protected String updatedBy;
    @XmlAttribute(name = "insertedTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar insertedTime;
    @XmlAttribute(name = "insertedBy")
    protected String insertedBy;
    @XmlAttribute(name = "deprecated")
    protected Boolean deprecated;
    @XmlAttribute(name = "newKey")
    protected String newKey;
    @XmlAttribute(name = "validFrom")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validFrom;
    @XmlAttribute(name = "validTo")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validTo;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public StringWithAnyAttributes getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public void setId(StringWithAnyAttributes value) {
        this.id = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public StringWithAnyAttributes getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public void setCode(StringWithAnyAttributes value) {
        this.code = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public StringWithAnyAttributes getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public void setRegion(StringWithAnyAttributes value) {
        this.region = value;
    }

    /**
     * Gets the value of the placename property.
     * 
     * @return
     *     possible object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public StringWithAnyAttributes getPlacename() {
        return placename;
    }

    /**
     * Sets the value of the placename property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public void setPlacename(StringWithAnyAttributes value) {
        this.placename = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public StringWithAnyAttributes getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public void setName(StringWithAnyAttributes value) {
        this.name = value;
    }

    /**
     * Gets the value of the buyerid property.
     * 
     * @return
     *     possible object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public StringWithAnyAttributes getBuyerid() {
        return buyerid;
    }

    /**
     * Sets the value of the buyerid property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public void setBuyerid(StringWithAnyAttributes value) {
        this.buyerid = value;
    }

    /**
     * Gets the value of the locationid property.
     * 
     * @return
     *     possible object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public StringWithAnyAttributes getLocationid() {
        return locationid;
    }

    /**
     * Sets the value of the locationid property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public void setLocationid(StringWithAnyAttributes value) {
        this.locationid = value;
    }

    /**
     * Gets the value of the locode property.
     * 
     * @return
     *     possible object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public StringWithAnyAttributes getLocode() {
        return locode;
    }

    /**
     * Sets the value of the locode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public void setLocode(StringWithAnyAttributes value) {
        this.locode = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public StringWithAnyAttributes getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public void setDescription(StringWithAnyAttributes value) {
        this.description = value;
    }

    /**
     * Gets the value of the updatedTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdatedTime() {
        return updatedTime;
    }

    /**
     * Sets the value of the updatedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdatedTime(XMLGregorianCalendar value) {
        this.updatedTime = value;
    }

    /**
     * Gets the value of the updatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * Sets the value of the updatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedBy(String value) {
        this.updatedBy = value;
    }

    /**
     * Gets the value of the insertedTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInsertedTime() {
        return insertedTime;
    }

    /**
     * Sets the value of the insertedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInsertedTime(XMLGregorianCalendar value) {
        this.insertedTime = value;
    }

    /**
     * Gets the value of the insertedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsertedBy() {
        return insertedBy;
    }

    /**
     * Sets the value of the insertedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsertedBy(String value) {
        this.insertedBy = value;
    }

    /**
     * Gets the value of the deprecated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeprecated() {
        return deprecated;
    }

    /**
     * Sets the value of the deprecated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeprecated(Boolean value) {
        this.deprecated = value;
    }

    /**
     * Gets the value of the newKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewKey() {
        return newKey;
    }

    /**
     * Sets the value of the newKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewKey(String value) {
        this.newKey = value;
    }

    /**
     * Gets the value of the validFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidFrom() {
        return validFrom;
    }

    /**
     * Sets the value of the validFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidFrom(XMLGregorianCalendar value) {
        this.validFrom = value;
    }

    /**
     * Gets the value of the validTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidTo() {
        return validTo;
    }

    /**
     * Sets the value of the validTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidTo(XMLGregorianCalendar value) {
        this.validTo = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
