//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 02:52:48 PM CEST 
//


package no.imr.formats.nmdreference.v2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.imr.formats.nmdreference.v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.imr.formats.nmdreference.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SurveyTimeSeriesCruiseSeriesType }
     * 
     */
    public SurveyTimeSeriesCruiseSeriesType createSurveyTimeSeriesCruiseSeriesType() {
        return new SurveyTimeSeriesCruiseSeriesType();
    }

    /**
     * Create an instance of {@link SurveyTimeSeriesType }
     * 
     */
    public SurveyTimeSeriesType createSurveyTimeSeriesType() {
        return new SurveyTimeSeriesType();
    }

    /**
     * Create an instance of {@link CruiseseriesSampleType }
     * 
     */
    public CruiseseriesSampleType createCruiseseriesSampleType() {
        return new CruiseseriesSampleType();
    }

    /**
     * Create an instance of {@link CruiseSeriesType }
     * 
     */
    public CruiseSeriesType createCruiseSeriesType() {
        return new CruiseSeriesType();
    }

    /**
     * Create an instance of {@link StockElementType }
     * 
     */
    public StockElementType createStockElementType() {
        return new StockElementType();
    }

    /**
     * Create an instance of {@link TaxaElementType }
     * 
     */
    public TaxaElementType createTaxaElementType() {
        return new TaxaElementType();
    }

    /**
     * Create an instance of {@link PlatformElementType }
     * 
     */
    public PlatformElementType createPlatformElementType() {
        return new PlatformElementType();
    }

    /**
     * Create an instance of {@link AgeReaderElementType }
     * 
     */
    public AgeReaderElementType createAgeReaderElementType() {
        return new AgeReaderElementType();
    }

    /**
     * Create an instance of {@link FAOSeaAreaElementType }
     * 
     */
    public FAOSeaAreaElementType createFAOSeaAreaElementType() {
        return new FAOSeaAreaElementType();
    }

    /**
     * Create an instance of {@link FAOFishingGearCategoryElementType }
     * 
     */
    public FAOFishingGearCategoryElementType createFAOFishingGearCategoryElementType() {
        return new FAOFishingGearCategoryElementType();
    }

    /**
     * Create an instance of {@link TableInfoType }
     * 
     */
    public TableInfoType createTableInfoType() {
        return new TableInfoType();
    }

    /**
     * Create an instance of {@link FAOFishingGearDetailElementType }
     * 
     */
    public FAOFishingGearDetailElementType createFAOFishingGearDetailElementType() {
        return new FAOFishingGearDetailElementType();
    }

    /**
     * Create an instance of {@link LandingsiteElementType }
     * 
     */
    public LandingsiteElementType createLandingsiteElementType() {
        return new LandingsiteElementType();
    }

    /**
     * Create an instance of {@link AcousticCategoryElementType }
     * 
     */
    public AcousticCategoryElementType createAcousticCategoryElementType() {
        return new AcousticCategoryElementType();
    }

    /**
     * Create an instance of {@link EquipmentElementType }
     * 
     */
    public EquipmentElementType createEquipmentElementType() {
        return new EquipmentElementType();
    }

    /**
     * Create an instance of {@link AgeReaderExperienceElementType }
     * 
     */
    public AgeReaderExperienceElementType createAgeReaderExperienceElementType() {
        return new AgeReaderExperienceElementType();
    }

    /**
     * Create an instance of {@link ExperienceElementType }
     * 
     */
    public ExperienceElementType createExperienceElementType() {
        return new ExperienceElementType();
    }

    /**
     * Create an instance of {@link TrawldoorElementType }
     * 
     */
    public TrawldoorElementType createTrawldoorElementType() {
        return new TrawldoorElementType();
    }

    /**
     * Create an instance of {@link MissionTypeElementType }
     * 
     */
    public MissionTypeElementType createMissionTypeElementType() {
        return new MissionTypeElementType();
    }

    /**
     * Create an instance of {@link LanguageElementType }
     * 
     */
    public LanguageElementType createLanguageElementType() {
        return new LanguageElementType();
    }

    /**
     * Create an instance of {@link ProjectElementType }
     * 
     */
    public ProjectElementType createProjectElementType() {
        return new ProjectElementType();
    }

    /**
     * Create an instance of {@link NationElementType }
     * 
     */
    public NationElementType createNationElementType() {
        return new NationElementType();
    }

    /**
     * Create an instance of {@link PlatformTypeElementType }
     * 
     */
    public PlatformTypeElementType createPlatformTypeElementType() {
        return new PlatformTypeElementType();
    }

    /**
     * Create an instance of {@link PlatformInstitutionElementType }
     * 
     */
    public PlatformInstitutionElementType createPlatformInstitutionElementType() {
        return new PlatformInstitutionElementType();
    }

    /**
     * Create an instance of {@link PlatformCodeElementType }
     * 
     */
    public PlatformCodeElementType createPlatformCodeElementType() {
        return new PlatformCodeElementType();
    }

    /**
     * Create an instance of {@link PlatformCodeSysElementType }
     * 
     */
    public PlatformCodeSysElementType createPlatformCodeSysElementType() {
        return new PlatformCodeSysElementType();
    }

    /**
     * Create an instance of {@link PersonElementType }
     * 
     */
    public PersonElementType createPersonElementType() {
        return new PersonElementType();
    }

    /**
     * Create an instance of {@link TaxaSynonymElementType }
     * 
     */
    public TaxaSynonymElementType createTaxaSynonymElementType() {
        return new TaxaSynonymElementType();
    }

    /**
     * Create an instance of {@link RestrictionElementType }
     * 
     */
    public RestrictionElementType createRestrictionElementType() {
        return new RestrictionElementType();
    }

    /**
     * Create an instance of {@link TaxaListElementType }
     * 
     */
    public TaxaListElementType createTaxaListElementType() {
        return new TaxaListElementType();
    }

    /**
     * Create an instance of {@link SeaAreaElementType }
     * 
     */
    public SeaAreaElementType createSeaAreaElementType() {
        return new SeaAreaElementType();
    }

    /**
     * Create an instance of {@link InstitutionElementType }
     * 
     */
    public InstitutionElementType createInstitutionElementType() {
        return new InstitutionElementType();
    }

    /**
     * Create an instance of {@link TableRef }
     * 
     */
    public TableRef createTableRef() {
        return new TableRef();
    }

    /**
     * Create an instance of {@link KeyValueElementType }
     * 
     */
    public KeyValueElementType createKeyValueElementType() {
        return new KeyValueElementType();
    }

    /**
     * Create an instance of {@link CruiseseriesCruiseType }
     * 
     */
    public CruiseseriesCruiseType createCruiseseriesCruiseType() {
        return new CruiseseriesCruiseType();
    }

    /**
     * Create an instance of {@link SurveyTimeSeriesSampleType }
     * 
     */
    public SurveyTimeSeriesSampleType createSurveyTimeSeriesSampleType() {
        return new SurveyTimeSeriesSampleType();
    }

    /**
     * Create an instance of {@link FixedCoastalstationType }
     * 
     */
    public FixedCoastalstationType createFixedCoastalstationType() {
        return new FixedCoastalstationType();
    }

    /**
     * Create an instance of {@link StationElementType }
     * 
     */
    public StationElementType createStationElementType() {
        return new StationElementType();
    }

    /**
     * Create an instance of {@link CSRSampleGroupElementType }
     * 
     */
    public CSRSampleGroupElementType createCSRSampleGroupElementType() {
        return new CSRSampleGroupElementType();
    }

    /**
     * Create an instance of {@link CSRSampleTypeElementType }
     * 
     */
    public CSRSampleTypeElementType createCSRSampleTypeElementType() {
        return new CSRSampleTypeElementType();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link TableRow }
     * 
     */
    public TableRow createTableRow() {
        return new TableRow();
    }

    /**
     * Create an instance of {@link ListType }
     * 
     */
    public ListType createListType() {
        return new ListType();
    }

    /**
     * Create an instance of {@link StringWithAnyAttributes }
     * 
     */
    public StringWithAnyAttributes createStringWithAnyAttributes() {
        return new StringWithAnyAttributes();
    }

    /**
     * Create an instance of {@link IntegerWithAnyAttributes }
     * 
     */
    public IntegerWithAnyAttributes createIntegerWithAnyAttributes() {
        return new IntegerWithAnyAttributes();
    }

    /**
     * Create an instance of {@link DecimalWithAnyAttributes }
     * 
     */
    public DecimalWithAnyAttributes createDecimalWithAnyAttributes() {
        return new DecimalWithAnyAttributes();
    }

    /**
     * Create an instance of {@link BooleanWithAnyAttributes }
     * 
     */
    public BooleanWithAnyAttributes createBooleanWithAnyAttributes() {
        return new BooleanWithAnyAttributes();
    }

    /**
     * Create an instance of {@link DateWithAnyAttributes }
     * 
     */
    public DateWithAnyAttributes createDateWithAnyAttributes() {
        return new DateWithAnyAttributes();
    }

    /**
     * Create an instance of {@link DateTimeWithAnyAttributes }
     * 
     */
    public DateTimeWithAnyAttributes createDateTimeWithAnyAttributes() {
        return new DateTimeWithAnyAttributes();
    }

    /**
     * Create an instance of {@link SurveyTimeSeriesCruiseSeriesType.Samples }
     * 
     */
    public SurveyTimeSeriesCruiseSeriesType.Samples createSurveyTimeSeriesCruiseSeriesTypeSamples() {
        return new SurveyTimeSeriesCruiseSeriesType.Samples();
    }

    /**
     * Create an instance of {@link SurveyTimeSeriesType.CruiseSeries }
     * 
     */
    public SurveyTimeSeriesType.CruiseSeries createSurveyTimeSeriesTypeCruiseSeries() {
        return new SurveyTimeSeriesType.CruiseSeries();
    }

    /**
     * Create an instance of {@link CruiseseriesSampleType.Cruises }
     * 
     */
    public CruiseseriesSampleType.Cruises createCruiseseriesSampleTypeCruises() {
        return new CruiseseriesSampleType.Cruises();
    }

    /**
     * Create an instance of {@link CruiseSeriesType.Samples }
     * 
     */
    public CruiseSeriesType.Samples createCruiseSeriesTypeSamples() {
        return new CruiseSeriesType.Samples();
    }

    /**
     * Create an instance of {@link StockElementType.Restrictions }
     * 
     */
    public StockElementType.Restrictions createStockElementTypeRestrictions() {
        return new StockElementType.Restrictions();
    }

    /**
     * Create an instance of {@link TaxaElementType.Restrictions }
     * 
     */
    public TaxaElementType.Restrictions createTaxaElementTypeRestrictions() {
        return new TaxaElementType.Restrictions();
    }

    /**
     * Create an instance of {@link TaxaElementType.Lists }
     * 
     */
    public TaxaElementType.Lists createTaxaElementTypeLists() {
        return new TaxaElementType.Lists();
    }

    /**
     * Create an instance of {@link TaxaElementType.TaxaSynonyms }
     * 
     */
    public TaxaElementType.TaxaSynonyms createTaxaElementTypeTaxaSynonyms() {
        return new TaxaElementType.TaxaSynonyms();
    }

    /**
     * Create an instance of {@link TaxaElementType.Stocks }
     * 
     */
    public TaxaElementType.Stocks createTaxaElementTypeStocks() {
        return new TaxaElementType.Stocks();
    }

    /**
     * Create an instance of {@link PlatformElementType.PlatformCodes }
     * 
     */
    public PlatformElementType.PlatformCodes createPlatformElementTypePlatformCodes() {
        return new PlatformElementType.PlatformCodes();
    }

    /**
     * Create an instance of {@link PlatformElementType.Institutions }
     * 
     */
    public PlatformElementType.Institutions createPlatformElementTypeInstitutions() {
        return new PlatformElementType.Institutions();
    }

    /**
     * Create an instance of {@link AgeReaderElementType.Experience }
     * 
     */
    public AgeReaderElementType.Experience createAgeReaderElementTypeExperience() {
        return new AgeReaderElementType.Experience();
    }

    /**
     * Create an instance of {@link FAOSeaAreaElementType.Subareas }
     * 
     */
    public FAOSeaAreaElementType.Subareas createFAOSeaAreaElementTypeSubareas() {
        return new FAOSeaAreaElementType.Subareas();
    }

    /**
     * Create an instance of {@link FAOFishingGearCategoryElementType.Details }
     * 
     */
    public FAOFishingGearCategoryElementType.Details createFAOFishingGearCategoryElementTypeDetails() {
        return new FAOFishingGearCategoryElementType.Details();
    }

}
