//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 02:52:48 PM CEST 
//


package no.imr.formats.nmdreference.v2;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * <p>Java class for PlatformElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlatformElementType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="platformNumber" type="{http://www.imr.no/formats/nmdreference/v2.0}StringWithAnyAttributes" minOccurs="0"/&gt;
 *         &lt;element name="nationCode" type="{http://www.imr.no/formats/nmdreference/v2.0}StringWithAnyAttributes" minOccurs="0"/&gt;
 *         &lt;element name="nation" type="{http://www.imr.no/formats/nmdreference/v2.0}StringWithAnyAttributes" minOccurs="0"/&gt;
 *         &lt;element name="platformTypeCode" type="{http://www.imr.no/formats/nmdreference/v2.0}StringWithAnyAttributes" minOccurs="0"/&gt;
 *         &lt;element name="platformType" type="{http://www.imr.no/formats/nmdreference/v2.0}StringWithAnyAttributes" minOccurs="0"/&gt;
 *         &lt;element name="platformSubType" type="{http://www.imr.no/formats/nmdreference/v2.0}StringWithAnyAttributes" minOccurs="0"/&gt;
 *         &lt;element name="description" type="{http://www.imr.no/formats/nmdreference/v2.0}StringWithAnyAttributes" minOccurs="0"/&gt;
 *         &lt;element name="platformCodes" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="platformCode" type="{http://www.imr.no/formats/nmdreference/v2.0}PlatformCodeElementType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="institutions" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="platformInstitution" type="{http://www.imr.no/formats/nmdreference/v2.0}PlatformInstitutionElementType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.imr.no/formats/nmdreference/v2.0}GenericAttrRowGroup"/&gt;
 *       &lt;attGroup ref="{http://www.imr.no/formats/nmdreference/v2.0}DeprecatedAttrGroup"/&gt;
 *       &lt;anyAttribute/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlatformElementType", propOrder = {
    "id",
    "platformNumber",
    "nationCode",
    "nation",
    "platformTypeCode",
    "platformType",
    "platformSubType",
    "description",
    "platformCodes",
    "institutions"
})
public class PlatformElementType {

    protected String id;
    protected StringWithAnyAttributes platformNumber;
    protected StringWithAnyAttributes nationCode;
    protected StringWithAnyAttributes nation;
    protected StringWithAnyAttributes platformTypeCode;
    protected StringWithAnyAttributes platformType;
    protected StringWithAnyAttributes platformSubType;
    protected StringWithAnyAttributes description;
    protected PlatformElementType.PlatformCodes platformCodes;
    protected PlatformElementType.Institutions institutions;
    @XmlAttribute(name = "updatedTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updatedTime;
    @XmlAttribute(name = "updatedBy")
    protected String updatedBy;
    @XmlAttribute(name = "insertedTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar insertedTime;
    @XmlAttribute(name = "insertedBy")
    protected String insertedBy;
    @XmlAttribute(name = "deprecated")
    protected Boolean deprecated;
    @XmlAttribute(name = "newKey")
    protected String newKey;
    @XmlAttribute(name = "validFrom")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validFrom;
    @XmlAttribute(name = "validTo")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validTo;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the platformNumber property.
     * 
     * @return
     *     possible object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public StringWithAnyAttributes getPlatformNumber() {
        return platformNumber;
    }

    /**
     * Sets the value of the platformNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public void setPlatformNumber(StringWithAnyAttributes value) {
        this.platformNumber = value;
    }

    /**
     * Gets the value of the nationCode property.
     * 
     * @return
     *     possible object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public StringWithAnyAttributes getNationCode() {
        return nationCode;
    }

    /**
     * Sets the value of the nationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public void setNationCode(StringWithAnyAttributes value) {
        this.nationCode = value;
    }

    /**
     * Gets the value of the nation property.
     * 
     * @return
     *     possible object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public StringWithAnyAttributes getNation() {
        return nation;
    }

    /**
     * Sets the value of the nation property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public void setNation(StringWithAnyAttributes value) {
        this.nation = value;
    }

    /**
     * Gets the value of the platformTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public StringWithAnyAttributes getPlatformTypeCode() {
        return platformTypeCode;
    }

    /**
     * Sets the value of the platformTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public void setPlatformTypeCode(StringWithAnyAttributes value) {
        this.platformTypeCode = value;
    }

    /**
     * Gets the value of the platformType property.
     * 
     * @return
     *     possible object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public StringWithAnyAttributes getPlatformType() {
        return platformType;
    }

    /**
     * Sets the value of the platformType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public void setPlatformType(StringWithAnyAttributes value) {
        this.platformType = value;
    }

    /**
     * Gets the value of the platformSubType property.
     * 
     * @return
     *     possible object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public StringWithAnyAttributes getPlatformSubType() {
        return platformSubType;
    }

    /**
     * Sets the value of the platformSubType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public void setPlatformSubType(StringWithAnyAttributes value) {
        this.platformSubType = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public StringWithAnyAttributes getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringWithAnyAttributes }
     *     
     */
    public void setDescription(StringWithAnyAttributes value) {
        this.description = value;
    }

    /**
     * Gets the value of the platformCodes property.
     * 
     * @return
     *     possible object is
     *     {@link PlatformElementType.PlatformCodes }
     *     
     */
    public PlatformElementType.PlatformCodes getPlatformCodes() {
        return platformCodes;
    }

    /**
     * Sets the value of the platformCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlatformElementType.PlatformCodes }
     *     
     */
    public void setPlatformCodes(PlatformElementType.PlatformCodes value) {
        this.platformCodes = value;
    }

    /**
     * Gets the value of the institutions property.
     * 
     * @return
     *     possible object is
     *     {@link PlatformElementType.Institutions }
     *     
     */
    public PlatformElementType.Institutions getInstitutions() {
        return institutions;
    }

    /**
     * Sets the value of the institutions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlatformElementType.Institutions }
     *     
     */
    public void setInstitutions(PlatformElementType.Institutions value) {
        this.institutions = value;
    }

    /**
     * Gets the value of the updatedTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdatedTime() {
        return updatedTime;
    }

    /**
     * Sets the value of the updatedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdatedTime(XMLGregorianCalendar value) {
        this.updatedTime = value;
    }

    /**
     * Gets the value of the updatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * Sets the value of the updatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedBy(String value) {
        this.updatedBy = value;
    }

    /**
     * Gets the value of the insertedTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInsertedTime() {
        return insertedTime;
    }

    /**
     * Sets the value of the insertedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInsertedTime(XMLGregorianCalendar value) {
        this.insertedTime = value;
    }

    /**
     * Gets the value of the insertedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsertedBy() {
        return insertedBy;
    }

    /**
     * Sets the value of the insertedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsertedBy(String value) {
        this.insertedBy = value;
    }

    /**
     * Gets the value of the deprecated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeprecated() {
        return deprecated;
    }

    /**
     * Sets the value of the deprecated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeprecated(Boolean value) {
        this.deprecated = value;
    }

    /**
     * Gets the value of the newKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewKey() {
        return newKey;
    }

    /**
     * Sets the value of the newKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewKey(String value) {
        this.newKey = value;
    }

    /**
     * Gets the value of the validFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidFrom() {
        return validFrom;
    }

    /**
     * Sets the value of the validFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidFrom(XMLGregorianCalendar value) {
        this.validFrom = value;
    }

    /**
     * Gets the value of the validTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidTo() {
        return validTo;
    }

    /**
     * Sets the value of the validTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidTo(XMLGregorianCalendar value) {
        this.validTo = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="platformInstitution" type="{http://www.imr.no/formats/nmdreference/v2.0}PlatformInstitutionElementType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "platformInstitution"
    })
    public static class Institutions {

        protected List<PlatformInstitutionElementType> platformInstitution;

        /**
         * Gets the value of the platformInstitution property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the platformInstitution property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPlatformInstitution().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PlatformInstitutionElementType }
         * 
         * 
         */
        public List<PlatformInstitutionElementType> getPlatformInstitution() {
            if (platformInstitution == null) {
                platformInstitution = new ArrayList<PlatformInstitutionElementType>();
            }
            return this.platformInstitution;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="platformCode" type="{http://www.imr.no/formats/nmdreference/v2.0}PlatformCodeElementType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "platformCode"
    })
    public static class PlatformCodes {

        protected List<PlatformCodeElementType> platformCode;

        /**
         * Gets the value of the platformCode property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the platformCode property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPlatformCode().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PlatformCodeElementType }
         * 
         * 
         */
        public List<PlatformCodeElementType> getPlatformCode() {
            if (platformCode == null) {
                platformCode = new ArrayList<PlatformCodeElementType>();
            }
            return this.platformCode;
        }

    }

}
