/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package no.imr.sea2data.stox.components.table;

import javax.swing.JTextArea;
import no.imr.stox.api.IProjectProvider;
import no.imr.stox.datastorage.IDataStorage;
import no.imr.stox.datastorage.ProcessDataStorage;
import no.imr.stox.functions.utils.Functions;
import no.imr.stox.model.IModel;
import no.imr.stox.model.IModelListener;
import no.imr.stox.model.IModelListenerService;
import no.imr.stox.model.IProcess;
import no.imr.stox.model.ModelListenerAdapter;
import org.openide.util.Lookup;

/**
 *
 * @author aasmunds
 */
public class OutputPanel extends javax.swing.JPanel {

    private String text;
    private String tabName;
    String modelName;
    String processName;
    int idx;
    IModelListener modelListener = new ModelListenerAdapter() {
        @Override
        public void onProcessEnd(IProcess process) {
            if (process == null) {
                return;
            }
            IProcess p = getProcess();
            if (p == null || p.getOutput() == null) {
                getTextArea().setText("");
                return;
            }
            IDataStorage ds = getDataStorage(p);
            if (process.equals(p) && ds != null) {
                String res = ds.asTable(p.getOutput(), idx + 1, true);
                setText(res);
            } else if (process.getProcessStep() < p.getProcessStep()) {
                getTextArea().setText("");
            }
        }

        @Override
        public void onReset(IModel m) {
            setText("");
        }
    };

    /**
     * Creates new form OutputPanel
     */
    public OutputPanel(IProcess p, int idx) {
        this.modelName = p.getModel().getModelName();
        this.processName = p.getName();
        this.idx = idx;
        initComponents();
        final IModelListenerService fls = (IModelListenerService) Lookup.getDefault().lookup(IModelListenerService.class);
        fls.getModelListeners().add(modelListener);
    }

    public static IDataStorage getDataStorage(IProcess p) {
        IDataStorage ds = p.getDataStorage();
        if (ds == null && p.getMetaFunction() != null && p.getMetaFunction().getOutputDataTypeName().equals(Functions.DT_PROCESSDATA)) {
            // Process Data with no datastorage inbuilt will create a temporarily here:
            ds = new ProcessDataStorage();
            ds.setProcess(p);
        }
        return ds;
    }

    IProcess getProcess() {
        IProjectProvider provider = (IProjectProvider) Lookup.getDefault().lookup(IProjectProvider.class);
        if (provider.getProject() == null) {
            return null;
        }
        IModel model = provider.getProject().getModel(modelName);
        if (model == null) {
            return null;
        }
        return model.getProcessFromName(processName);
    }

    public String getProcessName() {
        return processName;
    }

    public Integer getIdx() {
        return idx;
    }
    

    public JTextArea getTextArea() {
        return jTextArea2;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
        String res = FormattedOutput.formatTable(text);
        getTextArea().setText(res);
        getTextArea().setCaretPosition(0);
    }

    public void onClose() {
        final IModelListenerService fls = (IModelListenerService) Lookup.getDefault().lookup(IModelListenerService.class);
        fls.getModelListeners().remove(modelListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables

    void setTabName(String tabName) {
        this.tabName = tabName;
    }

    public String getTabName() {
        return tabName;
    }

}
