package no.imr.sea2data.stox.components.table;

import java.awt.BorderLayout;
import java.io.File;
import java.io.FileFilter;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import no.imr.guibase.controls.ImagePanel;
import no.imr.sea2data.imrbase.util.Workspace;
import no.imr.stox.functions.utils.Functions;
import no.imr.stox.functions.utils.ProjectUtils;
import no.imr.stox.model.IModel;
import no.imr.stox.model.IModelListenerService;
import no.imr.stox.model.IProcess;
import no.imr.stox.model.ModelListenerAdapter;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//no.imr.sea2data.stox.components.table//TableFrame//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "TableFrameTopComponent",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = true, position = 20)
@ActionID(category = "Window", id = "no.imr.sea2data.stox.components.table.TableFrameTopComponent")
@ActionReference(path = "Menu/Window")
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_TableFrameAction",
        preferredID = "TableFrameTopComponent")
public final class TableFrameTopComponent extends TopComponent {

    /**
     * Initialize.
     */
    public TableFrameTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(TableFrameTopComponent.class, "CTL_TableFrameTopComponent"));
        setToolTipText(NbBundle.getMessage(TableFrameTopComponent.class, "HINT_TableFrameTopComponent"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());
        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
        IModelListenerService fls = (IModelListenerService) Lookup.getDefault().lookup(IModelListenerService.class);
        fls.getModelListeners().add(new ModelListenerAdapter() {

            @Override
            public void onModelStart(IModel model) {
                TableFrameTopComponent.this.onModelStart(model);
            }

            @Override
            public void onModelStop(IModel model) {
                TableFrameTopComponent.this.onModelStop(model);
            }

            @Override
            public void onProcessEnd(IProcess process) {
                TableFrameTopComponent.this.onProcessEnd(process); //To change body of generated methods, choose Tools | Templates.
            }
        });

    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    /**
     * Required top component method.
     *
     * @param p Property object.
     */
    void writeProperties(final java.util.Properties p) {
        /**
         * Do nothing
         */
    }

    /**
     * Required top component method.
     *
     * @param p Property object.
     */
    void readProperties(final java.util.Properties p) {
        /**
         * Do nothing
         */
    }

    public JTextArea createTextTab(JTabbedPane pane, String tabText) {
        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());
        JTextArea textArea = new JTextArea();
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        textArea.setRows(5);
        JScrollPane sp = new JScrollPane();
        sp.setViewportView(textArea);
        panel.add(sp, java.awt.BorderLayout.CENTER);
        pane.addTab(tabText, panel);
        return textArea;
    }

    public void onModelStart(IModel model) {
        for (int tc = jTabbedPane1.getTabCount() - 1; tc >= 0; tc--) {
            jTabbedPane1.removeTabAt(tc);
        }
    }

    public void onModelStop(IModel model) {
        if (model.getModelName().equals(ProjectUtils.R_REPORT)) {
            String reportDir = Workspace.getDir(model.getProject().getProjectFolder(), ProjectUtils.PROJECT_OUTPUTR_REPORT);
            File f = new File(reportDir);
            File[] plotFiles = f.listFiles(new FileFilter() {

                @Override
                public boolean accept(File pathname) {
                    return pathname.isFile() && (pathname.getPath().endsWith("png"));
                }
            });
            for (File pl : plotFiles) {
                String plotName = pl.getName().replaceFirst("[.][^.]+$", "");
                JPanel imagePanel = new JPanel();
                ImagePanel imagePanel1 = new ImagePanel();
                imagePanel.add(imagePanel1, BorderLayout.CENTER);
                imagePanel1.setImage(pl.getPath());
                jTabbedPane1.addTab(plotName, imagePanel1);
            }
        }
    }

    public void onProcessEnd(IProcess process) {
        switch (process.getMetaFunction().getName()) {
            case Functions.FN_TOTALABUNDANCE:
                createTextTab(jTabbedPane1, "Abundance").setText(process.getDataStorage().asTable(process.getOutput(), 1));
                break;
            case Functions.FN_ESTIMATEBYPOPULATIONCATEGORY:
                createTextTab(jTabbedPane1, "Abundance").setText(process.getDataStorage().asTable(process.getOutput(), 1));
                createTextTab(jTabbedPane1, "Biomass").setText(process.getDataStorage().asTable(process.getOutput(), 2));
                createTextTab(jTabbedPane1, "Mean Weight").setText(process.getDataStorage().asTable(process.getOutput(), 3));
                break;
        }
    }
}
