/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package no.imr.stox.dlg;

import java.beans.PropertyEditor;
import javax.swing.table.DefaultTableModel;
import no.imr.sea2data.imrbase.util.Conversion;
import no.imr.sea2data.imrbase.util.ExportUtil;

/**
 *
 * @author aasmunds
 */
public class CatchabilityDlg extends javax.swing.JDialog {

    PropertyEditor ed;

    /**
     * Creates new form TablePropertyDlg
     */
    public CatchabilityDlg(PropertyEditor ed) {
        super((java.awt.Frame) null, true);
        this.ed = ed;
        initComponents();
        setTitle("Catchability table:");
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(jOK);
        DefaultTableModel dt = (DefaultTableModel) jTable.getModel();
        String txt = ed.getAsText();
        String lines[] = txt.split("/");
        for (int row = 0; row < lines.length; row++) {
            String line = lines[row];
            if (line.isEmpty()) {
                continue;
            }
            String cells[] = line.split(";");
            if (cells.length != 5) {
                continue;
            }
            String specCat = cells[0];
            Double alpha = Conversion.safeStringtoDoubleNULL(cells[1]);
            Double beta = Conversion.safeStringtoDoubleNULL(cells[2]);
            Double lmin = Conversion.safeStringtoDoubleNULL(cells[3]);
            Double lmax = Conversion.safeStringtoDoubleNULL(cells[4]);
            dt.setValueAt(specCat, row, 0);
            if (alpha != null) {
                dt.setValueAt(alpha, row, 1);
            }
            if (beta != null) {
                dt.setValueAt(beta, row, 2);
            }
            if (lmin != null) {
                dt.setValueAt(lmin, row, 3);
            }
            if (lmax != null) {
                dt.setValueAt(lmax, row, 4);
            }
            if (row > dt.getRowCount() - 1) {
                break; // limit
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.openide.awt.Mnemonics.setLocalizedText(jOK, org.openide.util.NbBundle.getMessage(CatchabilityDlg.class, "CatchabilityDlg.jOK.text")); // NOI18N
        jOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOKActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "SpecCat", "Alpha", "Beta", "LMin", "LMax"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable);
        jTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(CatchabilityDlg.class, "CatchabilityDlg.jTable.columnModel.title1")); // NOI18N
            jTable.getColumnModel().getColumn(1).setMinWidth(50);
            jTable.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable.getColumnModel().getColumn(1).setMaxWidth(50);
            jTable.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(CatchabilityDlg.class, "CatchabilityDlg.jTable.columnModel.title2")); // NOI18N
            jTable.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(CatchabilityDlg.class, "CatchabilityDlg.jTable.columnModel.title3")); // NOI18N
            jTable.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(CatchabilityDlg.class, "CatchabilityDlg.jTable.columnModel.title4")); // NOI18N
            jTable.getColumnModel().getColumn(4).setHeaderValue(org.openide.util.NbBundle.getMessage(CatchabilityDlg.class, "CatchabilityDlg.jTable.columnModel.title0_1")); // NOI18N
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jOK)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jOK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOKActionPerformed
        DefaultTableModel dt = (DefaultTableModel) jTable.getModel();
        String res = "";
        for (int row = 0; row < dt.getRowCount() - 1; row++) {
            String specCat = (String) dt.getValueAt(row, 0);
            Double alpha = (Double) dt.getValueAt(row, 1);
            Double beta = (Double) dt.getValueAt(row, 2);
            Double lmin = (Double) dt.getValueAt(row, 3);
            Double lmax = (Double) dt.getValueAt(row, 4);
            if (specCat == null && alpha == null && beta == null && lmin == null && lmax == null) {
                continue;
            }
            String line = ExportUtil.separated(';', specCat, alpha, beta, lmin, lmax);
            res += (res.isEmpty() ? "" : "/") + line;
        }
        ed.setAsText(res);
        setVisible(false);
    }//GEN-LAST:event_jOKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jOK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
