package no.imr.stox.dlg;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import no.imr.stox.model.IProject;

/**
 *
 * @author Åsmund
 */
public class SaveAsDlg extends javax.swing.JDialog {

    private final IProject project;

    /**
     * Creates new form SaveAsDlg
     */
    public SaveAsDlg(IProject project) {
        super((java.awt.Frame) null, true);
        initComponents();
        this.project = project;
        setLocationRelativeTo(null);
        setTitle("Save project as");
        getRootPane().setDefaultButton(jOK);
        jProjectname.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                updateProjectFolder();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateProjectFolder();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateProjectFolder();
            }
        });
        updateProjectFolder();
    }

    public String getProjectName() {
        return jProjectname.getText();
    }

    private void updateProjectFolder() {
        jProjectFolder.setText(project.getRootFolder() + "/" + jProjectname.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jProjectname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jProjectFolder = new javax.swing.JTextField();
        jOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(SaveAsDlg.class, "SaveAsDlg.jLabel1.text")); // NOI18N

        jProjectname.setText(org.openide.util.NbBundle.getMessage(SaveAsDlg.class, "SaveAsDlg.jProjectname.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(SaveAsDlg.class, "SaveAsDlg.jLabel2.text")); // NOI18N

        jProjectFolder.setEditable(false);
        jProjectFolder.setText(org.openide.util.NbBundle.getMessage(SaveAsDlg.class, "SaveAsDlg.jProjectFolder.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jOK, org.openide.util.NbBundle.getMessage(SaveAsDlg.class, "SaveAsDlg.jOK.text")); // NOI18N
        jOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProjectname)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 271, Short.MAX_VALUE))
                    .addComponent(jProjectFolder)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jOK, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProjectname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProjectFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOKActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jOKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jOK;
    private javax.swing.JTextField jProjectFolder;
    private javax.swing.JTextField jProjectname;
    // End of variables declaration//GEN-END:variables
}
