//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 02:52:48 PM CEST 
//


package BioticTypes.v3;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3._2001.xmlschema.Adapter1;


/**
 * <p>Java class for AgedeterminationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AgedeterminationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="agingstructureread" type="{http://www.imr.no/formats/nmdbiotic/v3}CompositeTaxaKeyType" minOccurs="0"/&gt;
 *         &lt;element name="agingstructureweight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="agingstructurelength" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="nowearpoint" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="externalspinebase" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="countedannualage" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="age" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="spawningage" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="smoltage" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="marineage" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="spawningzones" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="readability" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="otolithtype" type="{http://www.imr.no/formats/nmdbiotic/v3}CompositeTaxaKeyType" minOccurs="0"/&gt;
 *         &lt;element name="otolithedge" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="otolithcentre" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="calibration" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="growthzone1" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="growthzone2" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="growthzone3" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="growthzone4" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="growthzone5" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="growthzone6" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="growthzone7" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="growthzone8" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="growthzone9" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="growthzonestotal" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="coastalannuli" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="oceanicannuli" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="blindreading" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="readingdate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="agereader" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="agedeterminationid" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AgedeterminationType", propOrder = {
    "agingstructureread",
    "agingstructureweight",
    "agingstructurelength",
    "nowearpoint",
    "externalspinebase",
    "countedannualage",
    "age",
    "spawningage",
    "smoltage",
    "marineage",
    "spawningzones",
    "readability",
    "otolithtype",
    "otolithedge",
    "otolithcentre",
    "calibration",
    "growthzone1",
    "growthzone2",
    "growthzone3",
    "growthzone4",
    "growthzone5",
    "growthzone6",
    "growthzone7",
    "growthzone8",
    "growthzone9",
    "growthzonestotal",
    "coastalannuli",
    "oceanicannuli",
    "blindreading",
    "readingdate",
    "agereader"
})
public class AgedeterminationType {

    protected String agingstructureread;
    protected BigDecimal agingstructureweight;
    protected BigDecimal agingstructurelength;
    protected BigDecimal nowearpoint;
    protected BigDecimal externalspinebase;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer countedannualage;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer age;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer spawningage;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer smoltage;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer marineage;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer spawningzones;
    protected String readability;
    protected String otolithtype;
    protected String otolithedge;
    protected String otolithcentre;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer calibration;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer growthzone1;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer growthzone2;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer growthzone3;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer growthzone4;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer growthzone5;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer growthzone6;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer growthzone7;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer growthzone8;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer growthzone9;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer growthzonestotal;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer coastalannuli;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer oceanicannuli;
    protected String blindreading;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar readingdate;
    protected String agereader;
    @XmlAttribute(name = "agedeterminationid", required = true)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer agedeterminationid;

    /**
     * Gets the value of the agingstructureread property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgingstructureread() {
        return agingstructureread;
    }

    /**
     * Sets the value of the agingstructureread property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgingstructureread(String value) {
        this.agingstructureread = value;
    }

    /**
     * Gets the value of the agingstructureweight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAgingstructureweight() {
        return agingstructureweight;
    }

    /**
     * Sets the value of the agingstructureweight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAgingstructureweight(BigDecimal value) {
        this.agingstructureweight = value;
    }

    /**
     * Gets the value of the agingstructurelength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAgingstructurelength() {
        return agingstructurelength;
    }

    /**
     * Sets the value of the agingstructurelength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAgingstructurelength(BigDecimal value) {
        this.agingstructurelength = value;
    }

    /**
     * Gets the value of the nowearpoint property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNowearpoint() {
        return nowearpoint;
    }

    /**
     * Sets the value of the nowearpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNowearpoint(BigDecimal value) {
        this.nowearpoint = value;
    }

    /**
     * Gets the value of the externalspinebase property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExternalspinebase() {
        return externalspinebase;
    }

    /**
     * Sets the value of the externalspinebase property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExternalspinebase(BigDecimal value) {
        this.externalspinebase = value;
    }

    /**
     * Gets the value of the countedannualage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getCountedannualage() {
        return countedannualage;
    }

    /**
     * Sets the value of the countedannualage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountedannualage(Integer value) {
        this.countedannualage = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAge(Integer value) {
        this.age = value;
    }

    /**
     * Gets the value of the spawningage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getSpawningage() {
        return spawningage;
    }

    /**
     * Sets the value of the spawningage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpawningage(Integer value) {
        this.spawningage = value;
    }

    /**
     * Gets the value of the smoltage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getSmoltage() {
        return smoltage;
    }

    /**
     * Sets the value of the smoltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmoltage(Integer value) {
        this.smoltage = value;
    }

    /**
     * Gets the value of the marineage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getMarineage() {
        return marineage;
    }

    /**
     * Sets the value of the marineage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarineage(Integer value) {
        this.marineage = value;
    }

    /**
     * Gets the value of the spawningzones property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getSpawningzones() {
        return spawningzones;
    }

    /**
     * Sets the value of the spawningzones property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpawningzones(Integer value) {
        this.spawningzones = value;
    }

    /**
     * Gets the value of the readability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReadability() {
        return readability;
    }

    /**
     * Sets the value of the readability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReadability(String value) {
        this.readability = value;
    }

    /**
     * Gets the value of the otolithtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtolithtype() {
        return otolithtype;
    }

    /**
     * Sets the value of the otolithtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtolithtype(String value) {
        this.otolithtype = value;
    }

    /**
     * Gets the value of the otolithedge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtolithedge() {
        return otolithedge;
    }

    /**
     * Sets the value of the otolithedge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtolithedge(String value) {
        this.otolithedge = value;
    }

    /**
     * Gets the value of the otolithcentre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtolithcentre() {
        return otolithcentre;
    }

    /**
     * Sets the value of the otolithcentre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtolithcentre(String value) {
        this.otolithcentre = value;
    }

    /**
     * Gets the value of the calibration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getCalibration() {
        return calibration;
    }

    /**
     * Sets the value of the calibration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalibration(Integer value) {
        this.calibration = value;
    }

    /**
     * Gets the value of the growthzone1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getGrowthzone1() {
        return growthzone1;
    }

    /**
     * Sets the value of the growthzone1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrowthzone1(Integer value) {
        this.growthzone1 = value;
    }

    /**
     * Gets the value of the growthzone2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getGrowthzone2() {
        return growthzone2;
    }

    /**
     * Sets the value of the growthzone2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrowthzone2(Integer value) {
        this.growthzone2 = value;
    }

    /**
     * Gets the value of the growthzone3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getGrowthzone3() {
        return growthzone3;
    }

    /**
     * Sets the value of the growthzone3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrowthzone3(Integer value) {
        this.growthzone3 = value;
    }

    /**
     * Gets the value of the growthzone4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getGrowthzone4() {
        return growthzone4;
    }

    /**
     * Sets the value of the growthzone4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrowthzone4(Integer value) {
        this.growthzone4 = value;
    }

    /**
     * Gets the value of the growthzone5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getGrowthzone5() {
        return growthzone5;
    }

    /**
     * Sets the value of the growthzone5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrowthzone5(Integer value) {
        this.growthzone5 = value;
    }

    /**
     * Gets the value of the growthzone6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getGrowthzone6() {
        return growthzone6;
    }

    /**
     * Sets the value of the growthzone6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrowthzone6(Integer value) {
        this.growthzone6 = value;
    }

    /**
     * Gets the value of the growthzone7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getGrowthzone7() {
        return growthzone7;
    }

    /**
     * Sets the value of the growthzone7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrowthzone7(Integer value) {
        this.growthzone7 = value;
    }

    /**
     * Gets the value of the growthzone8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getGrowthzone8() {
        return growthzone8;
    }

    /**
     * Sets the value of the growthzone8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrowthzone8(Integer value) {
        this.growthzone8 = value;
    }

    /**
     * Gets the value of the growthzone9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getGrowthzone9() {
        return growthzone9;
    }

    /**
     * Sets the value of the growthzone9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrowthzone9(Integer value) {
        this.growthzone9 = value;
    }

    /**
     * Gets the value of the growthzonestotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getGrowthzonestotal() {
        return growthzonestotal;
    }

    /**
     * Sets the value of the growthzonestotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrowthzonestotal(Integer value) {
        this.growthzonestotal = value;
    }

    /**
     * Gets the value of the coastalannuli property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getCoastalannuli() {
        return coastalannuli;
    }

    /**
     * Sets the value of the coastalannuli property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoastalannuli(Integer value) {
        this.coastalannuli = value;
    }

    /**
     * Gets the value of the oceanicannuli property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getOceanicannuli() {
        return oceanicannuli;
    }

    /**
     * Sets the value of the oceanicannuli property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOceanicannuli(Integer value) {
        this.oceanicannuli = value;
    }

    /**
     * Gets the value of the blindreading property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlindreading() {
        return blindreading;
    }

    /**
     * Sets the value of the blindreading property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlindreading(String value) {
        this.blindreading = value;
    }

    /**
     * Gets the value of the readingdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReadingdate() {
        return readingdate;
    }

    /**
     * Sets the value of the readingdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReadingdate(XMLGregorianCalendar value) {
        this.readingdate = value;
    }

    /**
     * Gets the value of the agereader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgereader() {
        return agereader;
    }

    /**
     * Sets the value of the agereader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgereader(String value) {
        this.agereader = value;
    }

    /**
     * Gets the value of the agedeterminationid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getAgedeterminationid() {
        return agedeterminationid;
    }

    /**
     * Sets the value of the agedeterminationid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgedeterminationid(Integer value) {
        this.agedeterminationid = value;
    }

}
