//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 02:52:48 PM CEST 
//


package BioticTypes.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import no.imr.formats.nmdreference.v2.AgeReaderElementType;


/**
 * <p>Java class for AgereaderTableType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AgereaderTableType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.imr.no/formats/nmdbiotic/v3}ReferenceTableType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="reference" type="{http://www.imr.no/formats/nmdreference/v2.0}AgeReaderElementType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AgereaderTableType", propOrder = {
    "reference"
})
public class AgereaderTableType
    extends ReferenceTableType
{

    @XmlElement(required = true)
    protected List<AgeReaderElementType> reference;

    /**
     * Gets the value of the reference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgeReaderElementType }
     * 
     * 
     */
    public List<AgeReaderElementType> getReference() {
        if (reference == null) {
            reference = new ArrayList<AgeReaderElementType>();
        }
        return this.reference;
    }

}
