//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 02:52:48 PM CEST 
//


package BioticTypes.v3;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._2001.xmlschema.Adapter1;


/**
 * <p>Java class for CatchsampleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CatchsampleType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="commonname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="catchcategory" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="catchpartnumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="aphia" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType"/&gt;
 *         &lt;element name="scientificname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="identification" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="foreignobject" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="sampletype" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="group" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="conservation" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="catchproducttype" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="raisingfactor" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="catchweight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="catchvolume" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="catchcount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="abundancecategory" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="sampleproducttype" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="lengthmeasurement" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="lengthsampleweight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="lengthsamplevolume" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="lengthsamplecount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="specimensamplecount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="agesamplecount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="agingstructure" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="parasite" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="stomach" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="intestine" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="tissuesample" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="samplerecipient" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="catchcomment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="individual" type="{http://www.imr.no/formats/nmdbiotic/v3}IndividualType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="catchsampleid" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CatchsampleType", propOrder = {
    "commonname",
    "catchcategory",
    "catchpartnumber",
    "aphia",
    "scientificname",
    "identification",
    "foreignobject",
    "sampletype",
    "group",
    "conservation",
    "catchproducttype",
    "raisingfactor",
    "catchweight",
    "catchvolume",
    "catchcount",
    "abundancecategory",
    "sampleproducttype",
    "lengthmeasurement",
    "lengthsampleweight",
    "lengthsamplevolume",
    "lengthsamplecount",
    "specimensamplecount",
    "agesamplecount",
    "agingstructure",
    "parasite",
    "stomach",
    "intestine",
    "tissuesample",
    "samplerecipient",
    "catchcomment",
    "individual"
})
public class CatchsampleType {

    protected String commonname;
    protected String catchcategory;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer catchpartnumber;
    @XmlElement(required = true)
    protected String aphia;
    @XmlElement(required = true)
    protected String scientificname;
    protected String identification;
    protected String foreignobject;
    protected String sampletype;
    protected String group;
    protected String conservation;
    protected String catchproducttype;
    protected BigDecimal raisingfactor;
    protected BigDecimal catchweight;
    protected BigDecimal catchvolume;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer catchcount;
    protected String abundancecategory;
    protected String sampleproducttype;
    protected String lengthmeasurement;
    protected BigDecimal lengthsampleweight;
    protected BigDecimal lengthsamplevolume;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer lengthsamplecount;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer specimensamplecount;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer agesamplecount;
    protected String agingstructure;
    protected String parasite;
    protected String stomach;
    protected String intestine;
    protected String tissuesample;
    protected String samplerecipient;
    protected String catchcomment;
    protected List<IndividualType> individual;
    @XmlAttribute(name = "catchsampleid", required = true)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer catchsampleid;

    /**
     * Gets the value of the commonname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommonname() {
        return commonname;
    }

    /**
     * Sets the value of the commonname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommonname(String value) {
        this.commonname = value;
    }

    /**
     * Gets the value of the catchcategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatchcategory() {
        return catchcategory;
    }

    /**
     * Sets the value of the catchcategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatchcategory(String value) {
        this.catchcategory = value;
    }

    /**
     * Gets the value of the catchpartnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getCatchpartnumber() {
        return catchpartnumber;
    }

    /**
     * Sets the value of the catchpartnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatchpartnumber(Integer value) {
        this.catchpartnumber = value;
    }

    /**
     * Gets the value of the aphia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAphia() {
        return aphia;
    }

    /**
     * Sets the value of the aphia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAphia(String value) {
        this.aphia = value;
    }

    /**
     * Gets the value of the scientificname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScientificname() {
        return scientificname;
    }

    /**
     * Sets the value of the scientificname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScientificname(String value) {
        this.scientificname = value;
    }

    /**
     * Gets the value of the identification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentification() {
        return identification;
    }

    /**
     * Sets the value of the identification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentification(String value) {
        this.identification = value;
    }

    /**
     * Gets the value of the foreignobject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForeignobject() {
        return foreignobject;
    }

    /**
     * Sets the value of the foreignobject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForeignobject(String value) {
        this.foreignobject = value;
    }

    /**
     * Gets the value of the sampletype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampletype() {
        return sampletype;
    }

    /**
     * Sets the value of the sampletype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampletype(String value) {
        this.sampletype = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroup(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the conservation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConservation() {
        return conservation;
    }

    /**
     * Sets the value of the conservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConservation(String value) {
        this.conservation = value;
    }

    /**
     * Gets the value of the catchproducttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatchproducttype() {
        return catchproducttype;
    }

    /**
     * Sets the value of the catchproducttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatchproducttype(String value) {
        this.catchproducttype = value;
    }

    /**
     * Gets the value of the raisingfactor property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRaisingfactor() {
        return raisingfactor;
    }

    /**
     * Sets the value of the raisingfactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRaisingfactor(BigDecimal value) {
        this.raisingfactor = value;
    }

    /**
     * Gets the value of the catchweight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCatchweight() {
        return catchweight;
    }

    /**
     * Sets the value of the catchweight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCatchweight(BigDecimal value) {
        this.catchweight = value;
    }

    /**
     * Gets the value of the catchvolume property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCatchvolume() {
        return catchvolume;
    }

    /**
     * Sets the value of the catchvolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCatchvolume(BigDecimal value) {
        this.catchvolume = value;
    }

    /**
     * Gets the value of the catchcount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getCatchcount() {
        return catchcount;
    }

    /**
     * Sets the value of the catchcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatchcount(Integer value) {
        this.catchcount = value;
    }

    /**
     * Gets the value of the abundancecategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbundancecategory() {
        return abundancecategory;
    }

    /**
     * Sets the value of the abundancecategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbundancecategory(String value) {
        this.abundancecategory = value;
    }

    /**
     * Gets the value of the sampleproducttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampleproducttype() {
        return sampleproducttype;
    }

    /**
     * Sets the value of the sampleproducttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampleproducttype(String value) {
        this.sampleproducttype = value;
    }

    /**
     * Gets the value of the lengthmeasurement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLengthmeasurement() {
        return lengthmeasurement;
    }

    /**
     * Sets the value of the lengthmeasurement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLengthmeasurement(String value) {
        this.lengthmeasurement = value;
    }

    /**
     * Gets the value of the lengthsampleweight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLengthsampleweight() {
        return lengthsampleweight;
    }

    /**
     * Sets the value of the lengthsampleweight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLengthsampleweight(BigDecimal value) {
        this.lengthsampleweight = value;
    }

    /**
     * Gets the value of the lengthsamplevolume property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLengthsamplevolume() {
        return lengthsamplevolume;
    }

    /**
     * Sets the value of the lengthsamplevolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLengthsamplevolume(BigDecimal value) {
        this.lengthsamplevolume = value;
    }

    /**
     * Gets the value of the lengthsamplecount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getLengthsamplecount() {
        return lengthsamplecount;
    }

    /**
     * Sets the value of the lengthsamplecount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLengthsamplecount(Integer value) {
        this.lengthsamplecount = value;
    }

    /**
     * Gets the value of the specimensamplecount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getSpecimensamplecount() {
        return specimensamplecount;
    }

    /**
     * Sets the value of the specimensamplecount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecimensamplecount(Integer value) {
        this.specimensamplecount = value;
    }

    /**
     * Gets the value of the agesamplecount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getAgesamplecount() {
        return agesamplecount;
    }

    /**
     * Sets the value of the agesamplecount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgesamplecount(Integer value) {
        this.agesamplecount = value;
    }

    /**
     * Gets the value of the agingstructure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgingstructure() {
        return agingstructure;
    }

    /**
     * Sets the value of the agingstructure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgingstructure(String value) {
        this.agingstructure = value;
    }

    /**
     * Gets the value of the parasite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParasite() {
        return parasite;
    }

    /**
     * Sets the value of the parasite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParasite(String value) {
        this.parasite = value;
    }

    /**
     * Gets the value of the stomach property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStomach() {
        return stomach;
    }

    /**
     * Sets the value of the stomach property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStomach(String value) {
        this.stomach = value;
    }

    /**
     * Gets the value of the intestine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntestine() {
        return intestine;
    }

    /**
     * Sets the value of the intestine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntestine(String value) {
        this.intestine = value;
    }

    /**
     * Gets the value of the tissuesample property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTissuesample() {
        return tissuesample;
    }

    /**
     * Sets the value of the tissuesample property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTissuesample(String value) {
        this.tissuesample = value;
    }

    /**
     * Gets the value of the samplerecipient property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSamplerecipient() {
        return samplerecipient;
    }

    /**
     * Sets the value of the samplerecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSamplerecipient(String value) {
        this.samplerecipient = value;
    }

    /**
     * Gets the value of the catchcomment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatchcomment() {
        return catchcomment;
    }

    /**
     * Sets the value of the catchcomment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatchcomment(String value) {
        this.catchcomment = value;
    }

    /**
     * Gets the value of the individual property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the individual property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIndividual().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IndividualType }
     * 
     * 
     */
    public List<IndividualType> getIndividual() {
        if (individual == null) {
            individual = new ArrayList<IndividualType>();
        }
        return this.individual;
    }

    /**
     * Gets the value of the catchsampleid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getCatchsampleid() {
        return catchsampleid;
    }

    /**
     * Sets the value of the catchsampleid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatchsampleid(Integer value) {
        this.catchsampleid = value;
    }

}
