//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 02:52:48 PM CEST 
//


package BioticTypes.v3;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3._2001.xmlschema.Adapter1;


/**
 * <p>Java class for FishstationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FishstationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nation" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="catchplatform" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="station" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="fixedstation" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="stationstartdate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="stationstarttime" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/&gt;
 *         &lt;element name="stationstopdate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="stationstoptime" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/&gt;
 *         &lt;element name="stationtype" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="latitudestart" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="longitudestart" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="latitudeend" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="longitudeend" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="system" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="area" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="location" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="bottomdepthstart" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="bottomdepthstop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="bottomdepthmean" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="fishingdepthstart" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="fishingdepthstop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="fishingdepthcount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="fishingdepthmax" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="fishingdepthmin" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="fishingdepthmean" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="fishingdepthtemperature" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="gearno" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="sweeplength" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="gear" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="gearcount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="direction" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="gearflow" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="vesselspeed" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="logstart" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="logstop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="distance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="gearcondition" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="samplequality" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="verticaltrawlopening" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="verticaltrawlopeningsd" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="trawldoortype" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="trawldoorarea" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="trawldoorweight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="trawldoorspread" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="trawldoorspreadsd" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="wingspread" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="wingspreadsd" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="wirelength" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="wirediameter" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="wiredensity" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="soaktime" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="tripno" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="fishabundance" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="fishdistribution" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="landingsite" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="fishingground" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="vesselcount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="dataquality" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="haulvalidity" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="flora" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="vegetationcover" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="visibility" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="waterlevel" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="winddirection" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="windspeed" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="clouds" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="sea" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="weather" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="stationcomment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="catchsample" type="{http://www.imr.no/formats/nmdbiotic/v3}CatchsampleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="serialnumber" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FishstationType", propOrder = {
    "nation",
    "catchplatform",
    "station",
    "fixedstation",
    "stationstartdate",
    "stationstarttime",
    "stationstopdate",
    "stationstoptime",
    "stationtype",
    "latitudestart",
    "longitudestart",
    "latitudeend",
    "longitudeend",
    "system",
    "area",
    "location",
    "bottomdepthstart",
    "bottomdepthstop",
    "bottomdepthmean",
    "fishingdepthstart",
    "fishingdepthstop",
    "fishingdepthcount",
    "fishingdepthmax",
    "fishingdepthmin",
    "fishingdepthmean",
    "fishingdepthtemperature",
    "gearno",
    "sweeplength",
    "gear",
    "gearcount",
    "direction",
    "gearflow",
    "vesselspeed",
    "logstart",
    "logstop",
    "distance",
    "gearcondition",
    "samplequality",
    "verticaltrawlopening",
    "verticaltrawlopeningsd",
    "trawldoortype",
    "trawldoorarea",
    "trawldoorweight",
    "trawldoorspread",
    "trawldoorspreadsd",
    "wingspread",
    "wingspreadsd",
    "wirelength",
    "wirediameter",
    "wiredensity",
    "soaktime",
    "tripno",
    "fishabundance",
    "fishdistribution",
    "landingsite",
    "fishingground",
    "vesselcount",
    "dataquality",
    "haulvalidity",
    "flora",
    "vegetationcover",
    "visibility",
    "waterlevel",
    "winddirection",
    "windspeed",
    "clouds",
    "sea",
    "weather",
    "stationcomment",
    "catchsample"
})
public class FishstationType {

    protected String nation;
    protected String catchplatform;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer station;
    protected String fixedstation;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar stationstartdate;
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar stationstarttime;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar stationstopdate;
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar stationstoptime;
    protected String stationtype;
    protected BigDecimal latitudestart;
    protected BigDecimal longitudestart;
    protected BigDecimal latitudeend;
    protected BigDecimal longitudeend;
    protected String system;
    protected String area;
    protected String location;
    protected BigDecimal bottomdepthstart;
    protected BigDecimal bottomdepthstop;
    protected BigDecimal bottomdepthmean;
    protected BigDecimal fishingdepthstart;
    protected BigDecimal fishingdepthstop;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer fishingdepthcount;
    protected BigDecimal fishingdepthmax;
    protected BigDecimal fishingdepthmin;
    protected BigDecimal fishingdepthmean;
    protected BigDecimal fishingdepthtemperature;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer gearno;
    protected BigDecimal sweeplength;
    protected String gear;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer gearcount;
    protected BigDecimal direction;
    protected BigDecimal gearflow;
    protected BigDecimal vesselspeed;
    protected BigDecimal logstart;
    protected BigDecimal logstop;
    protected BigDecimal distance;
    protected String gearcondition;
    protected String samplequality;
    protected BigDecimal verticaltrawlopening;
    protected BigDecimal verticaltrawlopeningsd;
    protected String trawldoortype;
    protected BigDecimal trawldoorarea;
    protected BigDecimal trawldoorweight;
    protected BigDecimal trawldoorspread;
    protected BigDecimal trawldoorspreadsd;
    protected BigDecimal wingspread;
    protected BigDecimal wingspreadsd;
    protected BigDecimal wirelength;
    protected BigDecimal wirediameter;
    protected BigDecimal wiredensity;
    protected BigDecimal soaktime;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer tripno;
    protected String fishabundance;
    protected String fishdistribution;
    protected String landingsite;
    protected String fishingground;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer vesselcount;
    protected String dataquality;
    protected String haulvalidity;
    protected String flora;
    protected String vegetationcover;
    protected String visibility;
    protected BigDecimal waterlevel;
    protected BigDecimal winddirection;
    protected BigDecimal windspeed;
    protected String clouds;
    protected String sea;
    protected String weather;
    protected String stationcomment;
    protected List<CatchsampleType> catchsample;
    @XmlAttribute(name = "serialnumber", required = true)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer serialnumber;

    /**
     * Gets the value of the nation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNation() {
        return nation;
    }

    /**
     * Sets the value of the nation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNation(String value) {
        this.nation = value;
    }

    /**
     * Gets the value of the catchplatform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatchplatform() {
        return catchplatform;
    }

    /**
     * Sets the value of the catchplatform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatchplatform(String value) {
        this.catchplatform = value;
    }

    /**
     * Gets the value of the station property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getStation() {
        return station;
    }

    /**
     * Sets the value of the station property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStation(Integer value) {
        this.station = value;
    }

    /**
     * Gets the value of the fixedstation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixedstation() {
        return fixedstation;
    }

    /**
     * Sets the value of the fixedstation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixedstation(String value) {
        this.fixedstation = value;
    }

    /**
     * Gets the value of the stationstartdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStationstartdate() {
        return stationstartdate;
    }

    /**
     * Sets the value of the stationstartdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStationstartdate(XMLGregorianCalendar value) {
        this.stationstartdate = value;
    }

    /**
     * Gets the value of the stationstarttime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStationstarttime() {
        return stationstarttime;
    }

    /**
     * Sets the value of the stationstarttime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStationstarttime(XMLGregorianCalendar value) {
        this.stationstarttime = value;
    }

    /**
     * Gets the value of the stationstopdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStationstopdate() {
        return stationstopdate;
    }

    /**
     * Sets the value of the stationstopdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStationstopdate(XMLGregorianCalendar value) {
        this.stationstopdate = value;
    }

    /**
     * Gets the value of the stationstoptime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStationstoptime() {
        return stationstoptime;
    }

    /**
     * Sets the value of the stationstoptime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStationstoptime(XMLGregorianCalendar value) {
        this.stationstoptime = value;
    }

    /**
     * Gets the value of the stationtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStationtype() {
        return stationtype;
    }

    /**
     * Sets the value of the stationtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationtype(String value) {
        this.stationtype = value;
    }

    /**
     * Gets the value of the latitudestart property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLatitudestart() {
        return latitudestart;
    }

    /**
     * Sets the value of the latitudestart property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLatitudestart(BigDecimal value) {
        this.latitudestart = value;
    }

    /**
     * Gets the value of the longitudestart property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLongitudestart() {
        return longitudestart;
    }

    /**
     * Sets the value of the longitudestart property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLongitudestart(BigDecimal value) {
        this.longitudestart = value;
    }

    /**
     * Gets the value of the latitudeend property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLatitudeend() {
        return latitudeend;
    }

    /**
     * Sets the value of the latitudeend property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLatitudeend(BigDecimal value) {
        this.latitudeend = value;
    }

    /**
     * Gets the value of the longitudeend property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLongitudeend() {
        return longitudeend;
    }

    /**
     * Sets the value of the longitudeend property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLongitudeend(BigDecimal value) {
        this.longitudeend = value;
    }

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystem(String value) {
        this.system = value;
    }

    /**
     * Gets the value of the area property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArea() {
        return area;
    }

    /**
     * Sets the value of the area property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArea(String value) {
        this.area = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the bottomdepthstart property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBottomdepthstart() {
        return bottomdepthstart;
    }

    /**
     * Sets the value of the bottomdepthstart property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBottomdepthstart(BigDecimal value) {
        this.bottomdepthstart = value;
    }

    /**
     * Gets the value of the bottomdepthstop property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBottomdepthstop() {
        return bottomdepthstop;
    }

    /**
     * Sets the value of the bottomdepthstop property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBottomdepthstop(BigDecimal value) {
        this.bottomdepthstop = value;
    }

    /**
     * Gets the value of the bottomdepthmean property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBottomdepthmean() {
        return bottomdepthmean;
    }

    /**
     * Sets the value of the bottomdepthmean property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBottomdepthmean(BigDecimal value) {
        this.bottomdepthmean = value;
    }

    /**
     * Gets the value of the fishingdepthstart property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFishingdepthstart() {
        return fishingdepthstart;
    }

    /**
     * Sets the value of the fishingdepthstart property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFishingdepthstart(BigDecimal value) {
        this.fishingdepthstart = value;
    }

    /**
     * Gets the value of the fishingdepthstop property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFishingdepthstop() {
        return fishingdepthstop;
    }

    /**
     * Sets the value of the fishingdepthstop property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFishingdepthstop(BigDecimal value) {
        this.fishingdepthstop = value;
    }

    /**
     * Gets the value of the fishingdepthcount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getFishingdepthcount() {
        return fishingdepthcount;
    }

    /**
     * Sets the value of the fishingdepthcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFishingdepthcount(Integer value) {
        this.fishingdepthcount = value;
    }

    /**
     * Gets the value of the fishingdepthmax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFishingdepthmax() {
        return fishingdepthmax;
    }

    /**
     * Sets the value of the fishingdepthmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFishingdepthmax(BigDecimal value) {
        this.fishingdepthmax = value;
    }

    /**
     * Gets the value of the fishingdepthmin property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFishingdepthmin() {
        return fishingdepthmin;
    }

    /**
     * Sets the value of the fishingdepthmin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFishingdepthmin(BigDecimal value) {
        this.fishingdepthmin = value;
    }

    /**
     * Gets the value of the fishingdepthmean property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFishingdepthmean() {
        return fishingdepthmean;
    }

    /**
     * Sets the value of the fishingdepthmean property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFishingdepthmean(BigDecimal value) {
        this.fishingdepthmean = value;
    }

    /**
     * Gets the value of the fishingdepthtemperature property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFishingdepthtemperature() {
        return fishingdepthtemperature;
    }

    /**
     * Sets the value of the fishingdepthtemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFishingdepthtemperature(BigDecimal value) {
        this.fishingdepthtemperature = value;
    }

    /**
     * Gets the value of the gearno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getGearno() {
        return gearno;
    }

    /**
     * Sets the value of the gearno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGearno(Integer value) {
        this.gearno = value;
    }

    /**
     * Gets the value of the sweeplength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSweeplength() {
        return sweeplength;
    }

    /**
     * Sets the value of the sweeplength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSweeplength(BigDecimal value) {
        this.sweeplength = value;
    }

    /**
     * Gets the value of the gear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGear() {
        return gear;
    }

    /**
     * Sets the value of the gear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGear(String value) {
        this.gear = value;
    }

    /**
     * Gets the value of the gearcount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getGearcount() {
        return gearcount;
    }

    /**
     * Sets the value of the gearcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGearcount(Integer value) {
        this.gearcount = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDirection(BigDecimal value) {
        this.direction = value;
    }

    /**
     * Gets the value of the gearflow property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGearflow() {
        return gearflow;
    }

    /**
     * Sets the value of the gearflow property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGearflow(BigDecimal value) {
        this.gearflow = value;
    }

    /**
     * Gets the value of the vesselspeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVesselspeed() {
        return vesselspeed;
    }

    /**
     * Sets the value of the vesselspeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVesselspeed(BigDecimal value) {
        this.vesselspeed = value;
    }

    /**
     * Gets the value of the logstart property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLogstart() {
        return logstart;
    }

    /**
     * Sets the value of the logstart property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLogstart(BigDecimal value) {
        this.logstart = value;
    }

    /**
     * Gets the value of the logstop property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLogstop() {
        return logstop;
    }

    /**
     * Sets the value of the logstop property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLogstop(BigDecimal value) {
        this.logstop = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDistance(BigDecimal value) {
        this.distance = value;
    }

    /**
     * Gets the value of the gearcondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGearcondition() {
        return gearcondition;
    }

    /**
     * Sets the value of the gearcondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGearcondition(String value) {
        this.gearcondition = value;
    }

    /**
     * Gets the value of the samplequality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSamplequality() {
        return samplequality;
    }

    /**
     * Sets the value of the samplequality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSamplequality(String value) {
        this.samplequality = value;
    }

    /**
     * Gets the value of the verticaltrawlopening property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVerticaltrawlopening() {
        return verticaltrawlopening;
    }

    /**
     * Sets the value of the verticaltrawlopening property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVerticaltrawlopening(BigDecimal value) {
        this.verticaltrawlopening = value;
    }

    /**
     * Gets the value of the verticaltrawlopeningsd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVerticaltrawlopeningsd() {
        return verticaltrawlopeningsd;
    }

    /**
     * Sets the value of the verticaltrawlopeningsd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVerticaltrawlopeningsd(BigDecimal value) {
        this.verticaltrawlopeningsd = value;
    }

    /**
     * Gets the value of the trawldoortype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrawldoortype() {
        return trawldoortype;
    }

    /**
     * Sets the value of the trawldoortype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrawldoortype(String value) {
        this.trawldoortype = value;
    }

    /**
     * Gets the value of the trawldoorarea property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrawldoorarea() {
        return trawldoorarea;
    }

    /**
     * Sets the value of the trawldoorarea property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrawldoorarea(BigDecimal value) {
        this.trawldoorarea = value;
    }

    /**
     * Gets the value of the trawldoorweight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrawldoorweight() {
        return trawldoorweight;
    }

    /**
     * Sets the value of the trawldoorweight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrawldoorweight(BigDecimal value) {
        this.trawldoorweight = value;
    }

    /**
     * Gets the value of the trawldoorspread property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrawldoorspread() {
        return trawldoorspread;
    }

    /**
     * Sets the value of the trawldoorspread property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrawldoorspread(BigDecimal value) {
        this.trawldoorspread = value;
    }

    /**
     * Gets the value of the trawldoorspreadsd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrawldoorspreadsd() {
        return trawldoorspreadsd;
    }

    /**
     * Sets the value of the trawldoorspreadsd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrawldoorspreadsd(BigDecimal value) {
        this.trawldoorspreadsd = value;
    }

    /**
     * Gets the value of the wingspread property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWingspread() {
        return wingspread;
    }

    /**
     * Sets the value of the wingspread property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWingspread(BigDecimal value) {
        this.wingspread = value;
    }

    /**
     * Gets the value of the wingspreadsd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWingspreadsd() {
        return wingspreadsd;
    }

    /**
     * Sets the value of the wingspreadsd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWingspreadsd(BigDecimal value) {
        this.wingspreadsd = value;
    }

    /**
     * Gets the value of the wirelength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWirelength() {
        return wirelength;
    }

    /**
     * Sets the value of the wirelength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWirelength(BigDecimal value) {
        this.wirelength = value;
    }

    /**
     * Gets the value of the wirediameter property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWirediameter() {
        return wirediameter;
    }

    /**
     * Sets the value of the wirediameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWirediameter(BigDecimal value) {
        this.wirediameter = value;
    }

    /**
     * Gets the value of the wiredensity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWiredensity() {
        return wiredensity;
    }

    /**
     * Sets the value of the wiredensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWiredensity(BigDecimal value) {
        this.wiredensity = value;
    }

    /**
     * Gets the value of the soaktime property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSoaktime() {
        return soaktime;
    }

    /**
     * Sets the value of the soaktime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSoaktime(BigDecimal value) {
        this.soaktime = value;
    }

    /**
     * Gets the value of the tripno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getTripno() {
        return tripno;
    }

    /**
     * Sets the value of the tripno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTripno(Integer value) {
        this.tripno = value;
    }

    /**
     * Gets the value of the fishabundance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFishabundance() {
        return fishabundance;
    }

    /**
     * Sets the value of the fishabundance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFishabundance(String value) {
        this.fishabundance = value;
    }

    /**
     * Gets the value of the fishdistribution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFishdistribution() {
        return fishdistribution;
    }

    /**
     * Sets the value of the fishdistribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFishdistribution(String value) {
        this.fishdistribution = value;
    }

    /**
     * Gets the value of the landingsite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLandingsite() {
        return landingsite;
    }

    /**
     * Sets the value of the landingsite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLandingsite(String value) {
        this.landingsite = value;
    }

    /**
     * Gets the value of the fishingground property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFishingground() {
        return fishingground;
    }

    /**
     * Sets the value of the fishingground property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFishingground(String value) {
        this.fishingground = value;
    }

    /**
     * Gets the value of the vesselcount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getVesselcount() {
        return vesselcount;
    }

    /**
     * Sets the value of the vesselcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselcount(Integer value) {
        this.vesselcount = value;
    }

    /**
     * Gets the value of the dataquality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataquality() {
        return dataquality;
    }

    /**
     * Sets the value of the dataquality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataquality(String value) {
        this.dataquality = value;
    }

    /**
     * Gets the value of the haulvalidity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHaulvalidity() {
        return haulvalidity;
    }

    /**
     * Sets the value of the haulvalidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHaulvalidity(String value) {
        this.haulvalidity = value;
    }

    /**
     * Gets the value of the flora property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlora() {
        return flora;
    }

    /**
     * Sets the value of the flora property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlora(String value) {
        this.flora = value;
    }

    /**
     * Gets the value of the vegetationcover property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVegetationcover() {
        return vegetationcover;
    }

    /**
     * Sets the value of the vegetationcover property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVegetationcover(String value) {
        this.vegetationcover = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisibility(String value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the waterlevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWaterlevel() {
        return waterlevel;
    }

    /**
     * Sets the value of the waterlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWaterlevel(BigDecimal value) {
        this.waterlevel = value;
    }

    /**
     * Gets the value of the winddirection property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWinddirection() {
        return winddirection;
    }

    /**
     * Sets the value of the winddirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWinddirection(BigDecimal value) {
        this.winddirection = value;
    }

    /**
     * Gets the value of the windspeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWindspeed() {
        return windspeed;
    }

    /**
     * Sets the value of the windspeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWindspeed(BigDecimal value) {
        this.windspeed = value;
    }

    /**
     * Gets the value of the clouds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClouds() {
        return clouds;
    }

    /**
     * Sets the value of the clouds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClouds(String value) {
        this.clouds = value;
    }

    /**
     * Gets the value of the sea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSea() {
        return sea;
    }

    /**
     * Sets the value of the sea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSea(String value) {
        this.sea = value;
    }

    /**
     * Gets the value of the weather property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeather() {
        return weather;
    }

    /**
     * Sets the value of the weather property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeather(String value) {
        this.weather = value;
    }

    /**
     * Gets the value of the stationcomment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStationcomment() {
        return stationcomment;
    }

    /**
     * Sets the value of the stationcomment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationcomment(String value) {
        this.stationcomment = value;
    }

    /**
     * Gets the value of the catchsample property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the catchsample property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCatchsample().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CatchsampleType }
     * 
     * 
     */
    public List<CatchsampleType> getCatchsample() {
        if (catchsample == null) {
            catchsample = new ArrayList<CatchsampleType>();
        }
        return this.catchsample;
    }

    /**
     * Gets the value of the serialnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getSerialnumber() {
        return serialnumber;
    }

    /**
     * Sets the value of the serialnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialnumber(Integer value) {
        this.serialnumber = value;
    }

}
