//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 02:52:48 PM CEST 
//


package BioticTypes.v3;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._2001.xmlschema.Adapter1;


/**
 * <p>Java class for IndividualType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IndividualType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="individualproducttype" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="individualweight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="individualvolume" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="lengthresolution" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="length" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="fat" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="fatpercent" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="sex" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="maturationstage" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="specialstage" type="{http://www.imr.no/formats/nmdbiotic/v3}CompositeTaxaSexKeyType" minOccurs="0"/&gt;
 *         &lt;element name="eggstage" type="{http://www.imr.no/formats/nmdbiotic/v3}CompositeTaxaSexKeyType" minOccurs="0"/&gt;
 *         &lt;element name="moultingstage" type="{http://www.imr.no/formats/nmdbiotic/v3}CompositeTaxaKeyType" minOccurs="0"/&gt;
 *         &lt;element name="spawningfrequency" type="{http://www.imr.no/formats/nmdbiotic/v3}CompositeTaxaKeyType" minOccurs="0"/&gt;
 *         &lt;element name="stomachfillfield" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="stomachfilllab" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="digestion" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="liver" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="liverparasite" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="gillworms" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="swollengills" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="fungusheart" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="fungusspores" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="fungusouter" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="blackspot" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="vertebraecount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="gonadweight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="liverweight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="stomachweight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="diameter" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="mantlelength" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="carapacelength" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="headlength" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="snouttoendoftail" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="snouttoendsqueezed" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="snouttoanalfin" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="snouttodorsalfin" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="forklength" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="snouttoboneknob" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="lengthwithouthead" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="carapacewidth" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="rightclawwidth" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="rightclawlength" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="meroswidth" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="meroslength" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="japanesecut" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="abdomenwidth" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="tissuesamplenumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="individualcomment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="preferredagereading" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="agedetermination" type="{http://www.imr.no/formats/nmdbiotic/v3}AgedeterminationType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="tag" type="{http://www.imr.no/formats/nmdbiotic/v3}TagType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="prey" type="{http://www.imr.no/formats/nmdbiotic/v3}PreyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="specimenid" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IndividualType", propOrder = {
    "individualproducttype",
    "individualweight",
    "individualvolume",
    "lengthresolution",
    "length",
    "fat",
    "fatpercent",
    "sex",
    "maturationstage",
    "specialstage",
    "eggstage",
    "moultingstage",
    "spawningfrequency",
    "stomachfillfield",
    "stomachfilllab",
    "digestion",
    "liver",
    "liverparasite",
    "gillworms",
    "swollengills",
    "fungusheart",
    "fungusspores",
    "fungusouter",
    "blackspot",
    "vertebraecount",
    "gonadweight",
    "liverweight",
    "stomachweight",
    "diameter",
    "mantlelength",
    "carapacelength",
    "headlength",
    "snouttoendoftail",
    "snouttoendsqueezed",
    "snouttoanalfin",
    "snouttodorsalfin",
    "forklength",
    "snouttoboneknob",
    "lengthwithouthead",
    "carapacewidth",
    "rightclawwidth",
    "rightclawlength",
    "meroswidth",
    "meroslength",
    "japanesecut",
    "abdomenwidth",
    "tissuesamplenumber",
    "individualcomment",
    "preferredagereading",
    "agedetermination",
    "tag",
    "prey"
})
public class IndividualType {

    protected String individualproducttype;
    protected BigDecimal individualweight;
    protected BigDecimal individualvolume;
    protected String lengthresolution;
    protected BigDecimal length;
    protected String fat;
    protected BigDecimal fatpercent;
    protected String sex;
    protected String maturationstage;
    protected String specialstage;
    protected String eggstage;
    protected String moultingstage;
    protected String spawningfrequency;
    protected String stomachfillfield;
    protected String stomachfilllab;
    protected String digestion;
    protected String liver;
    protected String liverparasite;
    protected String gillworms;
    protected String swollengills;
    protected String fungusheart;
    protected String fungusspores;
    protected String fungusouter;
    protected String blackspot;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer vertebraecount;
    protected BigDecimal gonadweight;
    protected BigDecimal liverweight;
    protected BigDecimal stomachweight;
    protected BigDecimal diameter;
    protected BigDecimal mantlelength;
    protected BigDecimal carapacelength;
    protected BigDecimal headlength;
    protected BigDecimal snouttoendoftail;
    protected BigDecimal snouttoendsqueezed;
    protected BigDecimal snouttoanalfin;
    protected BigDecimal snouttodorsalfin;
    protected BigDecimal forklength;
    protected BigDecimal snouttoboneknob;
    protected BigDecimal lengthwithouthead;
    protected BigDecimal carapacewidth;
    protected BigDecimal rightclawwidth;
    protected BigDecimal rightclawlength;
    protected BigDecimal meroswidth;
    protected BigDecimal meroslength;
    protected BigDecimal japanesecut;
    protected BigDecimal abdomenwidth;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer tissuesamplenumber;
    protected String individualcomment;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer preferredagereading;
    protected List<AgedeterminationType> agedetermination;
    protected List<TagType> tag;
    protected List<PreyType> prey;
    @XmlAttribute(name = "specimenid", required = true)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer specimenid;

    /**
     * Gets the value of the individualproducttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndividualproducttype() {
        return individualproducttype;
    }

    /**
     * Sets the value of the individualproducttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndividualproducttype(String value) {
        this.individualproducttype = value;
    }

    /**
     * Gets the value of the individualweight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIndividualweight() {
        return individualweight;
    }

    /**
     * Sets the value of the individualweight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIndividualweight(BigDecimal value) {
        this.individualweight = value;
    }

    /**
     * Gets the value of the individualvolume property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIndividualvolume() {
        return individualvolume;
    }

    /**
     * Sets the value of the individualvolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIndividualvolume(BigDecimal value) {
        this.individualvolume = value;
    }

    /**
     * Gets the value of the lengthresolution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLengthresolution() {
        return lengthresolution;
    }

    /**
     * Sets the value of the lengthresolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLengthresolution(String value) {
        this.lengthresolution = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLength(BigDecimal value) {
        this.length = value;
    }

    /**
     * Gets the value of the fat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFat() {
        return fat;
    }

    /**
     * Sets the value of the fat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFat(String value) {
        this.fat = value;
    }

    /**
     * Gets the value of the fatpercent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFatpercent() {
        return fatpercent;
    }

    /**
     * Sets the value of the fatpercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFatpercent(BigDecimal value) {
        this.fatpercent = value;
    }

    /**
     * Gets the value of the sex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSex() {
        return sex;
    }

    /**
     * Sets the value of the sex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSex(String value) {
        this.sex = value;
    }

    /**
     * Gets the value of the maturationstage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaturationstage() {
        return maturationstage;
    }

    /**
     * Sets the value of the maturationstage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaturationstage(String value) {
        this.maturationstage = value;
    }

    /**
     * Gets the value of the specialstage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialstage() {
        return specialstage;
    }

    /**
     * Sets the value of the specialstage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialstage(String value) {
        this.specialstage = value;
    }

    /**
     * Gets the value of the eggstage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEggstage() {
        return eggstage;
    }

    /**
     * Sets the value of the eggstage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEggstage(String value) {
        this.eggstage = value;
    }

    /**
     * Gets the value of the moultingstage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoultingstage() {
        return moultingstage;
    }

    /**
     * Sets the value of the moultingstage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoultingstage(String value) {
        this.moultingstage = value;
    }

    /**
     * Gets the value of the spawningfrequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpawningfrequency() {
        return spawningfrequency;
    }

    /**
     * Sets the value of the spawningfrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpawningfrequency(String value) {
        this.spawningfrequency = value;
    }

    /**
     * Gets the value of the stomachfillfield property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStomachfillfield() {
        return stomachfillfield;
    }

    /**
     * Sets the value of the stomachfillfield property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStomachfillfield(String value) {
        this.stomachfillfield = value;
    }

    /**
     * Gets the value of the stomachfilllab property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStomachfilllab() {
        return stomachfilllab;
    }

    /**
     * Sets the value of the stomachfilllab property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStomachfilllab(String value) {
        this.stomachfilllab = value;
    }

    /**
     * Gets the value of the digestion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigestion() {
        return digestion;
    }

    /**
     * Sets the value of the digestion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigestion(String value) {
        this.digestion = value;
    }

    /**
     * Gets the value of the liver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLiver() {
        return liver;
    }

    /**
     * Sets the value of the liver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLiver(String value) {
        this.liver = value;
    }

    /**
     * Gets the value of the liverparasite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLiverparasite() {
        return liverparasite;
    }

    /**
     * Sets the value of the liverparasite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLiverparasite(String value) {
        this.liverparasite = value;
    }

    /**
     * Gets the value of the gillworms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGillworms() {
        return gillworms;
    }

    /**
     * Sets the value of the gillworms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGillworms(String value) {
        this.gillworms = value;
    }

    /**
     * Gets the value of the swollengills property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwollengills() {
        return swollengills;
    }

    /**
     * Sets the value of the swollengills property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwollengills(String value) {
        this.swollengills = value;
    }

    /**
     * Gets the value of the fungusheart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFungusheart() {
        return fungusheart;
    }

    /**
     * Sets the value of the fungusheart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFungusheart(String value) {
        this.fungusheart = value;
    }

    /**
     * Gets the value of the fungusspores property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFungusspores() {
        return fungusspores;
    }

    /**
     * Sets the value of the fungusspores property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFungusspores(String value) {
        this.fungusspores = value;
    }

    /**
     * Gets the value of the fungusouter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFungusouter() {
        return fungusouter;
    }

    /**
     * Sets the value of the fungusouter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFungusouter(String value) {
        this.fungusouter = value;
    }

    /**
     * Gets the value of the blackspot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlackspot() {
        return blackspot;
    }

    /**
     * Sets the value of the blackspot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlackspot(String value) {
        this.blackspot = value;
    }

    /**
     * Gets the value of the vertebraecount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getVertebraecount() {
        return vertebraecount;
    }

    /**
     * Sets the value of the vertebraecount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVertebraecount(Integer value) {
        this.vertebraecount = value;
    }

    /**
     * Gets the value of the gonadweight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGonadweight() {
        return gonadweight;
    }

    /**
     * Sets the value of the gonadweight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGonadweight(BigDecimal value) {
        this.gonadweight = value;
    }

    /**
     * Gets the value of the liverweight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLiverweight() {
        return liverweight;
    }

    /**
     * Sets the value of the liverweight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLiverweight(BigDecimal value) {
        this.liverweight = value;
    }

    /**
     * Gets the value of the stomachweight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStomachweight() {
        return stomachweight;
    }

    /**
     * Sets the value of the stomachweight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStomachweight(BigDecimal value) {
        this.stomachweight = value;
    }

    /**
     * Gets the value of the diameter property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiameter() {
        return diameter;
    }

    /**
     * Sets the value of the diameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiameter(BigDecimal value) {
        this.diameter = value;
    }

    /**
     * Gets the value of the mantlelength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMantlelength() {
        return mantlelength;
    }

    /**
     * Sets the value of the mantlelength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMantlelength(BigDecimal value) {
        this.mantlelength = value;
    }

    /**
     * Gets the value of the carapacelength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCarapacelength() {
        return carapacelength;
    }

    /**
     * Sets the value of the carapacelength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCarapacelength(BigDecimal value) {
        this.carapacelength = value;
    }

    /**
     * Gets the value of the headlength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHeadlength() {
        return headlength;
    }

    /**
     * Sets the value of the headlength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHeadlength(BigDecimal value) {
        this.headlength = value;
    }

    /**
     * Gets the value of the snouttoendoftail property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSnouttoendoftail() {
        return snouttoendoftail;
    }

    /**
     * Sets the value of the snouttoendoftail property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSnouttoendoftail(BigDecimal value) {
        this.snouttoendoftail = value;
    }

    /**
     * Gets the value of the snouttoendsqueezed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSnouttoendsqueezed() {
        return snouttoendsqueezed;
    }

    /**
     * Sets the value of the snouttoendsqueezed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSnouttoendsqueezed(BigDecimal value) {
        this.snouttoendsqueezed = value;
    }

    /**
     * Gets the value of the snouttoanalfin property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSnouttoanalfin() {
        return snouttoanalfin;
    }

    /**
     * Sets the value of the snouttoanalfin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSnouttoanalfin(BigDecimal value) {
        this.snouttoanalfin = value;
    }

    /**
     * Gets the value of the snouttodorsalfin property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSnouttodorsalfin() {
        return snouttodorsalfin;
    }

    /**
     * Sets the value of the snouttodorsalfin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSnouttodorsalfin(BigDecimal value) {
        this.snouttodorsalfin = value;
    }

    /**
     * Gets the value of the forklength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getForklength() {
        return forklength;
    }

    /**
     * Sets the value of the forklength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setForklength(BigDecimal value) {
        this.forklength = value;
    }

    /**
     * Gets the value of the snouttoboneknob property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSnouttoboneknob() {
        return snouttoboneknob;
    }

    /**
     * Sets the value of the snouttoboneknob property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSnouttoboneknob(BigDecimal value) {
        this.snouttoboneknob = value;
    }

    /**
     * Gets the value of the lengthwithouthead property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLengthwithouthead() {
        return lengthwithouthead;
    }

    /**
     * Sets the value of the lengthwithouthead property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLengthwithouthead(BigDecimal value) {
        this.lengthwithouthead = value;
    }

    /**
     * Gets the value of the carapacewidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCarapacewidth() {
        return carapacewidth;
    }

    /**
     * Sets the value of the carapacewidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCarapacewidth(BigDecimal value) {
        this.carapacewidth = value;
    }

    /**
     * Gets the value of the rightclawwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRightclawwidth() {
        return rightclawwidth;
    }

    /**
     * Sets the value of the rightclawwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRightclawwidth(BigDecimal value) {
        this.rightclawwidth = value;
    }

    /**
     * Gets the value of the rightclawlength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRightclawlength() {
        return rightclawlength;
    }

    /**
     * Sets the value of the rightclawlength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRightclawlength(BigDecimal value) {
        this.rightclawlength = value;
    }

    /**
     * Gets the value of the meroswidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMeroswidth() {
        return meroswidth;
    }

    /**
     * Sets the value of the meroswidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMeroswidth(BigDecimal value) {
        this.meroswidth = value;
    }

    /**
     * Gets the value of the meroslength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMeroslength() {
        return meroslength;
    }

    /**
     * Sets the value of the meroslength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMeroslength(BigDecimal value) {
        this.meroslength = value;
    }

    /**
     * Gets the value of the japanesecut property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getJapanesecut() {
        return japanesecut;
    }

    /**
     * Sets the value of the japanesecut property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setJapanesecut(BigDecimal value) {
        this.japanesecut = value;
    }

    /**
     * Gets the value of the abdomenwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAbdomenwidth() {
        return abdomenwidth;
    }

    /**
     * Sets the value of the abdomenwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAbdomenwidth(BigDecimal value) {
        this.abdomenwidth = value;
    }

    /**
     * Gets the value of the tissuesamplenumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getTissuesamplenumber() {
        return tissuesamplenumber;
    }

    /**
     * Sets the value of the tissuesamplenumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTissuesamplenumber(Integer value) {
        this.tissuesamplenumber = value;
    }

    /**
     * Gets the value of the individualcomment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndividualcomment() {
        return individualcomment;
    }

    /**
     * Sets the value of the individualcomment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndividualcomment(String value) {
        this.individualcomment = value;
    }

    /**
     * Gets the value of the preferredagereading property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getPreferredagereading() {
        return preferredagereading;
    }

    /**
     * Sets the value of the preferredagereading property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredagereading(Integer value) {
        this.preferredagereading = value;
    }

    /**
     * Gets the value of the agedetermination property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agedetermination property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgedetermination().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgedeterminationType }
     * 
     * 
     */
    public List<AgedeterminationType> getAgedetermination() {
        if (agedetermination == null) {
            agedetermination = new ArrayList<AgedeterminationType>();
        }
        return this.agedetermination;
    }

    /**
     * Gets the value of the tag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TagType }
     * 
     * 
     */
    public List<TagType> getTag() {
        if (tag == null) {
            tag = new ArrayList<TagType>();
        }
        return this.tag;
    }

    /**
     * Gets the value of the prey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PreyType }
     * 
     * 
     */
    public List<PreyType> getPrey() {
        if (prey == null) {
            prey = new ArrayList<PreyType>();
        }
        return this.prey;
    }

    /**
     * Gets the value of the specimenid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getSpecimenid() {
        return specimenid;
    }

    /**
     * Sets the value of the specimenid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecimenid(Integer value) {
        this.specimenid = value;
    }

}
