//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 02:52:48 PM CEST 
//


package BioticTypes.v3;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import org.w3._2001.xmlschema.Adapter1;


/**
 * <p>Java class for MissionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MissionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="missiontypename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="callsignal" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="platformname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cruise" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="missionstartdate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="missionstopdate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="purpose" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fishstation" type="{http://www.imr.no/formats/nmdbiotic/v3}FishstationType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="missiontype" use="required" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" /&gt;
 *       &lt;attribute name="startyear" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="platform" use="required" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" /&gt;
 *       &lt;attribute name="missionnumber" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;anyAttribute/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MissionType", propOrder = {
    "missiontypename",
    "callsignal",
    "platformname",
    "cruise",
    "missionstartdate",
    "missionstopdate",
    "purpose",
    "fishstation"
})
public class MissionType {

    @XmlElement(required = true)
    protected String missiontypename;
    @XmlElement(required = true)
    protected String callsignal;
    @XmlElement(required = true)
    protected String platformname;
    protected String cruise;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar missionstartdate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar missionstopdate;
    protected String purpose;
    protected List<FishstationType> fishstation;
    @XmlAttribute(name = "missiontype", required = true)
    protected String missiontype;
    @XmlAttribute(name = "startyear", required = true)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer startyear;
    @XmlAttribute(name = "platform", required = true)
    protected String platform;
    @XmlAttribute(name = "missionnumber", required = true)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer missionnumber;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the missiontypename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMissiontypename() {
        return missiontypename;
    }

    /**
     * Sets the value of the missiontypename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMissiontypename(String value) {
        this.missiontypename = value;
    }

    /**
     * Gets the value of the callsignal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallsignal() {
        return callsignal;
    }

    /**
     * Sets the value of the callsignal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallsignal(String value) {
        this.callsignal = value;
    }

    /**
     * Gets the value of the platformname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatformname() {
        return platformname;
    }

    /**
     * Sets the value of the platformname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatformname(String value) {
        this.platformname = value;
    }

    /**
     * Gets the value of the cruise property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCruise() {
        return cruise;
    }

    /**
     * Sets the value of the cruise property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCruise(String value) {
        this.cruise = value;
    }

    /**
     * Gets the value of the missionstartdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMissionstartdate() {
        return missionstartdate;
    }

    /**
     * Sets the value of the missionstartdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMissionstartdate(XMLGregorianCalendar value) {
        this.missionstartdate = value;
    }

    /**
     * Gets the value of the missionstopdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMissionstopdate() {
        return missionstopdate;
    }

    /**
     * Sets the value of the missionstopdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMissionstopdate(XMLGregorianCalendar value) {
        this.missionstopdate = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurpose(String value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the fishstation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fishstation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFishstation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FishstationType }
     * 
     * 
     */
    public List<FishstationType> getFishstation() {
        if (fishstation == null) {
            fishstation = new ArrayList<FishstationType>();
        }
        return this.fishstation;
    }

    /**
     * Gets the value of the missiontype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMissiontype() {
        return missiontype;
    }

    /**
     * Sets the value of the missiontype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMissiontype(String value) {
        this.missiontype = value;
    }

    /**
     * Gets the value of the startyear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getStartyear() {
        return startyear;
    }

    /**
     * Sets the value of the startyear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartyear(Integer value) {
        this.startyear = value;
    }

    /**
     * Gets the value of the platform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * Sets the value of the platform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatform(String value) {
        this.platform = value;
    }

    /**
     * Gets the value of the missionnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getMissionnumber() {
        return missionnumber;
    }

    /**
     * Sets the value of the missionnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMissionnumber(Integer value) {
        this.missionnumber = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
