//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 02:52:48 PM CEST 
//


package BioticTypes.v3;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._2001.xmlschema.Adapter1;


/**
 * <p>Java class for PreyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PreyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="preypartnumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="preycategory" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="source" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="preydigestion" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="totalcount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="weightresolution" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="totalweight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="interval" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="devstage" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="preylengthmeasurement" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *         &lt;element name="preylengthfrequencytable" type="{http://www.imr.no/formats/nmdbiotic/v3}PreylengthType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="copepodedevstagefrequencytable" type="{http://www.imr.no/formats/nmdbiotic/v3}CopepodedevstageType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="preysampleid" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreyType", propOrder = {
    "preypartnumber",
    "preycategory",
    "source",
    "preydigestion",
    "totalcount",
    "weightresolution",
    "totalweight",
    "interval",
    "devstage",
    "preylengthmeasurement",
    "preylengthfrequencytable",
    "copepodedevstagefrequencytable"
})
public class PreyType {

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer preypartnumber;
    protected String preycategory;
    protected String source;
    protected String preydigestion;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer totalcount;
    protected String weightresolution;
    protected BigDecimal totalweight;
    protected String interval;
    protected String devstage;
    protected String preylengthmeasurement;
    protected List<PreylengthType> preylengthfrequencytable;
    protected List<CopepodedevstageType> copepodedevstagefrequencytable;
    @XmlAttribute(name = "preysampleid", required = true)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer preysampleid;

    /**
     * Gets the value of the preypartnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getPreypartnumber() {
        return preypartnumber;
    }

    /**
     * Sets the value of the preypartnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreypartnumber(Integer value) {
        this.preypartnumber = value;
    }

    /**
     * Gets the value of the preycategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreycategory() {
        return preycategory;
    }

    /**
     * Sets the value of the preycategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreycategory(String value) {
        this.preycategory = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the preydigestion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreydigestion() {
        return preydigestion;
    }

    /**
     * Sets the value of the preydigestion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreydigestion(String value) {
        this.preydigestion = value;
    }

    /**
     * Gets the value of the totalcount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getTotalcount() {
        return totalcount;
    }

    /**
     * Sets the value of the totalcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalcount(Integer value) {
        this.totalcount = value;
    }

    /**
     * Gets the value of the weightresolution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeightresolution() {
        return weightresolution;
    }

    /**
     * Sets the value of the weightresolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeightresolution(String value) {
        this.weightresolution = value;
    }

    /**
     * Gets the value of the totalweight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalweight() {
        return totalweight;
    }

    /**
     * Sets the value of the totalweight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalweight(BigDecimal value) {
        this.totalweight = value;
    }

    /**
     * Gets the value of the interval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterval() {
        return interval;
    }

    /**
     * Sets the value of the interval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterval(String value) {
        this.interval = value;
    }

    /**
     * Gets the value of the devstage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDevstage() {
        return devstage;
    }

    /**
     * Sets the value of the devstage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDevstage(String value) {
        this.devstage = value;
    }

    /**
     * Gets the value of the preylengthmeasurement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreylengthmeasurement() {
        return preylengthmeasurement;
    }

    /**
     * Sets the value of the preylengthmeasurement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreylengthmeasurement(String value) {
        this.preylengthmeasurement = value;
    }

    /**
     * Gets the value of the preylengthfrequencytable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the preylengthfrequencytable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPreylengthfrequencytable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PreylengthType }
     * 
     * 
     */
    public List<PreylengthType> getPreylengthfrequencytable() {
        if (preylengthfrequencytable == null) {
            preylengthfrequencytable = new ArrayList<PreylengthType>();
        }
        return this.preylengthfrequencytable;
    }

    /**
     * Gets the value of the copepodedevstagefrequencytable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the copepodedevstagefrequencytable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCopepodedevstagefrequencytable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CopepodedevstageType }
     * 
     * 
     */
    public List<CopepodedevstageType> getCopepodedevstagefrequencytable() {
        if (copepodedevstagefrequencytable == null) {
            copepodedevstagefrequencytable = new ArrayList<CopepodedevstageType>();
        }
        return this.copepodedevstagefrequencytable;
    }

    /**
     * Gets the value of the preysampleid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getPreysampleid() {
        return preysampleid;
    }

    /**
     * Sets the value of the preysampleid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreysampleid(Integer value) {
        this.preysampleid = value;
    }

}
