//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 02:52:48 PM CEST 
//


package BioticTypes.v3;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._2001.xmlschema.Adapter1;


/**
 * <p>Java class for PreylengthType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PreylengthType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="lengthintervalstart" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="lengthintervalcount" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="preylengthid" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreylengthType", propOrder = {
    "lengthintervalstart",
    "lengthintervalcount"
})
public class PreylengthType {

    @XmlElement(required = true)
    protected BigDecimal lengthintervalstart;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer lengthintervalcount;
    @XmlAttribute(name = "preylengthid")
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer preylengthid;

    /**
     * Gets the value of the lengthintervalstart property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLengthintervalstart() {
        return lengthintervalstart;
    }

    /**
     * Sets the value of the lengthintervalstart property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLengthintervalstart(BigDecimal value) {
        this.lengthintervalstart = value;
    }

    /**
     * Gets the value of the lengthintervalcount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getLengthintervalcount() {
        return lengthintervalcount;
    }

    /**
     * Sets the value of the lengthintervalcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLengthintervalcount(Integer value) {
        this.lengthintervalcount = value;
    }

    /**
     * Gets the value of the preylengthid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getPreylengthid() {
        return preylengthid;
    }

    /**
     * Sets the value of the preylengthid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreylengthid(Integer value) {
        this.preylengthid = value;
    }

}
