//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 02:52:48 PM CEST 
//


package BioticTypes.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReferenceTablesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReferenceTablesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="missiontypetable" type="{http://www.imr.no/formats/nmdbiotic/v3}MissiontypeTableType"/&gt;
 *         &lt;element name="platformtable" type="{http://www.imr.no/formats/nmdbiotic/v3}PlatformTableType"/&gt;
 *         &lt;element name="nationtable" type="{http://www.imr.no/formats/nmdbiotic/v3}NationTableType"/&gt;
 *         &lt;element name="fixedstationtable" type="{http://www.imr.no/formats/nmdbiotic/v3}FixedstationTableType"/&gt;
 *         &lt;element name="stationtypetable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="systemtable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="geartable" type="{http://www.imr.no/formats/nmdbiotic/v3}GearTableType"/&gt;
 *         &lt;element name="gearconditiontable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="samplequalitytable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="trawldoortypetable" type="{http://www.imr.no/formats/nmdbiotic/v3}TrawldoorTableType"/&gt;
 *         &lt;element name="fishabundancetable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="fishdistributiontable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="landingssitetable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="fishinggroundtable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="dataqualitytable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="floratable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="vegetationcovertable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="visibilitytable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="haulvaliditytable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="cloudstable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="seatable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="weathertable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="taxatable" type="{http://www.imr.no/formats/nmdbiotic/v3}TaxaTableType"/&gt;
 *         &lt;element name="identificationtable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="sampletypetable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="grouptable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="conservationtable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="producttypetable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="abundancecategorytable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="lengthmeasurementtable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="agingstructuretable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="parasitetable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="stomachtable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="intestinetable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="tissuesampletable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="samplerecipienttable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="foreignobjecttable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="lengthresolutiontable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="fattable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="sextable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="maturationstagetable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="stomachfilltable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="digestiontable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="livertable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="liverparasitetable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="gillwormstable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="swollengillstable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="fungushearttable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="fungussporestable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="fungusoutertable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="blackspottable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="readabilitytable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="otolithedgetable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="otolithcentretable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="blindreadingtable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="agereadertable" type="{http://www.imr.no/formats/nmdbiotic/v3}AgereaderTableType"/&gt;
 *         &lt;element name="tagtypetable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="preysourcetable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="weightresolutiontable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="devstagetable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *         &lt;element name="copepodedevstagetable" type="{http://www.imr.no/formats/nmdbiotic/v3}ListTableType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReferenceTablesType", propOrder = {
    "missiontypetable",
    "platformtable",
    "nationtable",
    "fixedstationtable",
    "stationtypetable",
    "systemtable",
    "geartable",
    "gearconditiontable",
    "samplequalitytable",
    "trawldoortypetable",
    "fishabundancetable",
    "fishdistributiontable",
    "landingssitetable",
    "fishinggroundtable",
    "dataqualitytable",
    "floratable",
    "vegetationcovertable",
    "visibilitytable",
    "haulvaliditytable",
    "cloudstable",
    "seatable",
    "weathertable",
    "taxatable",
    "identificationtable",
    "sampletypetable",
    "grouptable",
    "conservationtable",
    "producttypetable",
    "abundancecategorytable",
    "lengthmeasurementtable",
    "agingstructuretable",
    "parasitetable",
    "stomachtable",
    "intestinetable",
    "tissuesampletable",
    "samplerecipienttable",
    "foreignobjecttable",
    "lengthresolutiontable",
    "fattable",
    "sextable",
    "maturationstagetable",
    "stomachfilltable",
    "digestiontable",
    "livertable",
    "liverparasitetable",
    "gillwormstable",
    "swollengillstable",
    "fungushearttable",
    "fungussporestable",
    "fungusoutertable",
    "blackspottable",
    "readabilitytable",
    "otolithedgetable",
    "otolithcentretable",
    "blindreadingtable",
    "agereadertable",
    "tagtypetable",
    "preysourcetable",
    "weightresolutiontable",
    "devstagetable",
    "copepodedevstagetable"
})
public class ReferenceTablesType {

    @XmlElement(required = true)
    protected MissiontypeTableType missiontypetable;
    @XmlElement(required = true)
    protected PlatformTableType platformtable;
    @XmlElement(required = true)
    protected NationTableType nationtable;
    @XmlElement(required = true)
    protected FixedstationTableType fixedstationtable;
    @XmlElement(required = true)
    protected ListTableType stationtypetable;
    @XmlElement(required = true)
    protected ListTableType systemtable;
    @XmlElement(required = true)
    protected GearTableType geartable;
    @XmlElement(required = true)
    protected ListTableType gearconditiontable;
    @XmlElement(required = true)
    protected ListTableType samplequalitytable;
    @XmlElement(required = true)
    protected TrawldoorTableType trawldoortypetable;
    @XmlElement(required = true)
    protected ListTableType fishabundancetable;
    @XmlElement(required = true)
    protected ListTableType fishdistributiontable;
    @XmlElement(required = true)
    protected ListTableType landingssitetable;
    @XmlElement(required = true)
    protected ListTableType fishinggroundtable;
    @XmlElement(required = true)
    protected ListTableType dataqualitytable;
    @XmlElement(required = true)
    protected ListTableType floratable;
    @XmlElement(required = true)
    protected ListTableType vegetationcovertable;
    @XmlElement(required = true)
    protected ListTableType visibilitytable;
    @XmlElement(required = true)
    protected ListTableType haulvaliditytable;
    @XmlElement(required = true)
    protected ListTableType cloudstable;
    @XmlElement(required = true)
    protected ListTableType seatable;
    @XmlElement(required = true)
    protected ListTableType weathertable;
    @XmlElement(required = true)
    protected TaxaTableType taxatable;
    @XmlElement(required = true)
    protected ListTableType identificationtable;
    @XmlElement(required = true)
    protected ListTableType sampletypetable;
    @XmlElement(required = true)
    protected ListTableType grouptable;
    @XmlElement(required = true)
    protected ListTableType conservationtable;
    @XmlElement(required = true)
    protected ListTableType producttypetable;
    @XmlElement(required = true)
    protected ListTableType abundancecategorytable;
    @XmlElement(required = true)
    protected ListTableType lengthmeasurementtable;
    @XmlElement(required = true)
    protected ListTableType agingstructuretable;
    @XmlElement(required = true)
    protected ListTableType parasitetable;
    @XmlElement(required = true)
    protected ListTableType stomachtable;
    @XmlElement(required = true)
    protected ListTableType intestinetable;
    @XmlElement(required = true)
    protected ListTableType tissuesampletable;
    @XmlElement(required = true)
    protected ListTableType samplerecipienttable;
    @XmlElement(required = true)
    protected ListTableType foreignobjecttable;
    @XmlElement(required = true)
    protected ListTableType lengthresolutiontable;
    @XmlElement(required = true)
    protected ListTableType fattable;
    @XmlElement(required = true)
    protected ListTableType sextable;
    @XmlElement(required = true)
    protected ListTableType maturationstagetable;
    @XmlElement(required = true)
    protected ListTableType stomachfilltable;
    @XmlElement(required = true)
    protected ListTableType digestiontable;
    @XmlElement(required = true)
    protected ListTableType livertable;
    @XmlElement(required = true)
    protected ListTableType liverparasitetable;
    @XmlElement(required = true)
    protected ListTableType gillwormstable;
    @XmlElement(required = true)
    protected ListTableType swollengillstable;
    @XmlElement(required = true)
    protected ListTableType fungushearttable;
    @XmlElement(required = true)
    protected ListTableType fungussporestable;
    @XmlElement(required = true)
    protected ListTableType fungusoutertable;
    @XmlElement(required = true)
    protected ListTableType blackspottable;
    @XmlElement(required = true)
    protected ListTableType readabilitytable;
    @XmlElement(required = true)
    protected ListTableType otolithedgetable;
    @XmlElement(required = true)
    protected ListTableType otolithcentretable;
    @XmlElement(required = true)
    protected ListTableType blindreadingtable;
    @XmlElement(required = true)
    protected AgereaderTableType agereadertable;
    @XmlElement(required = true)
    protected ListTableType tagtypetable;
    @XmlElement(required = true)
    protected ListTableType preysourcetable;
    @XmlElement(required = true)
    protected ListTableType weightresolutiontable;
    @XmlElement(required = true)
    protected ListTableType devstagetable;
    @XmlElement(required = true)
    protected ListTableType copepodedevstagetable;

    /**
     * Gets the value of the missiontypetable property.
     * 
     * @return
     *     possible object is
     *     {@link MissiontypeTableType }
     *     
     */
    public MissiontypeTableType getMissiontypetable() {
        return missiontypetable;
    }

    /**
     * Sets the value of the missiontypetable property.
     * 
     * @param value
     *     allowed object is
     *     {@link MissiontypeTableType }
     *     
     */
    public void setMissiontypetable(MissiontypeTableType value) {
        this.missiontypetable = value;
    }

    /**
     * Gets the value of the platformtable property.
     * 
     * @return
     *     possible object is
     *     {@link PlatformTableType }
     *     
     */
    public PlatformTableType getPlatformtable() {
        return platformtable;
    }

    /**
     * Sets the value of the platformtable property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlatformTableType }
     *     
     */
    public void setPlatformtable(PlatformTableType value) {
        this.platformtable = value;
    }

    /**
     * Gets the value of the nationtable property.
     * 
     * @return
     *     possible object is
     *     {@link NationTableType }
     *     
     */
    public NationTableType getNationtable() {
        return nationtable;
    }

    /**
     * Sets the value of the nationtable property.
     * 
     * @param value
     *     allowed object is
     *     {@link NationTableType }
     *     
     */
    public void setNationtable(NationTableType value) {
        this.nationtable = value;
    }

    /**
     * Gets the value of the fixedstationtable property.
     * 
     * @return
     *     possible object is
     *     {@link FixedstationTableType }
     *     
     */
    public FixedstationTableType getFixedstationtable() {
        return fixedstationtable;
    }

    /**
     * Sets the value of the fixedstationtable property.
     * 
     * @param value
     *     allowed object is
     *     {@link FixedstationTableType }
     *     
     */
    public void setFixedstationtable(FixedstationTableType value) {
        this.fixedstationtable = value;
    }

    /**
     * Gets the value of the stationtypetable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getStationtypetable() {
        return stationtypetable;
    }

    /**
     * Sets the value of the stationtypetable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setStationtypetable(ListTableType value) {
        this.stationtypetable = value;
    }

    /**
     * Gets the value of the systemtable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getSystemtable() {
        return systemtable;
    }

    /**
     * Sets the value of the systemtable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setSystemtable(ListTableType value) {
        this.systemtable = value;
    }

    /**
     * Gets the value of the geartable property.
     * 
     * @return
     *     possible object is
     *     {@link GearTableType }
     *     
     */
    public GearTableType getGeartable() {
        return geartable;
    }

    /**
     * Sets the value of the geartable property.
     * 
     * @param value
     *     allowed object is
     *     {@link GearTableType }
     *     
     */
    public void setGeartable(GearTableType value) {
        this.geartable = value;
    }

    /**
     * Gets the value of the gearconditiontable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getGearconditiontable() {
        return gearconditiontable;
    }

    /**
     * Sets the value of the gearconditiontable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setGearconditiontable(ListTableType value) {
        this.gearconditiontable = value;
    }

    /**
     * Gets the value of the samplequalitytable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getSamplequalitytable() {
        return samplequalitytable;
    }

    /**
     * Sets the value of the samplequalitytable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setSamplequalitytable(ListTableType value) {
        this.samplequalitytable = value;
    }

    /**
     * Gets the value of the trawldoortypetable property.
     * 
     * @return
     *     possible object is
     *     {@link TrawldoorTableType }
     *     
     */
    public TrawldoorTableType getTrawldoortypetable() {
        return trawldoortypetable;
    }

    /**
     * Sets the value of the trawldoortypetable property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrawldoorTableType }
     *     
     */
    public void setTrawldoortypetable(TrawldoorTableType value) {
        this.trawldoortypetable = value;
    }

    /**
     * Gets the value of the fishabundancetable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getFishabundancetable() {
        return fishabundancetable;
    }

    /**
     * Sets the value of the fishabundancetable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setFishabundancetable(ListTableType value) {
        this.fishabundancetable = value;
    }

    /**
     * Gets the value of the fishdistributiontable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getFishdistributiontable() {
        return fishdistributiontable;
    }

    /**
     * Sets the value of the fishdistributiontable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setFishdistributiontable(ListTableType value) {
        this.fishdistributiontable = value;
    }

    /**
     * Gets the value of the landingssitetable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getLandingssitetable() {
        return landingssitetable;
    }

    /**
     * Sets the value of the landingssitetable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setLandingssitetable(ListTableType value) {
        this.landingssitetable = value;
    }

    /**
     * Gets the value of the fishinggroundtable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getFishinggroundtable() {
        return fishinggroundtable;
    }

    /**
     * Sets the value of the fishinggroundtable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setFishinggroundtable(ListTableType value) {
        this.fishinggroundtable = value;
    }

    /**
     * Gets the value of the dataqualitytable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getDataqualitytable() {
        return dataqualitytable;
    }

    /**
     * Sets the value of the dataqualitytable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setDataqualitytable(ListTableType value) {
        this.dataqualitytable = value;
    }

    /**
     * Gets the value of the floratable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getFloratable() {
        return floratable;
    }

    /**
     * Sets the value of the floratable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setFloratable(ListTableType value) {
        this.floratable = value;
    }

    /**
     * Gets the value of the vegetationcovertable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getVegetationcovertable() {
        return vegetationcovertable;
    }

    /**
     * Sets the value of the vegetationcovertable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setVegetationcovertable(ListTableType value) {
        this.vegetationcovertable = value;
    }

    /**
     * Gets the value of the visibilitytable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getVisibilitytable() {
        return visibilitytable;
    }

    /**
     * Sets the value of the visibilitytable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setVisibilitytable(ListTableType value) {
        this.visibilitytable = value;
    }

    /**
     * Gets the value of the haulvaliditytable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getHaulvaliditytable() {
        return haulvaliditytable;
    }

    /**
     * Sets the value of the haulvaliditytable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setHaulvaliditytable(ListTableType value) {
        this.haulvaliditytable = value;
    }

    /**
     * Gets the value of the cloudstable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getCloudstable() {
        return cloudstable;
    }

    /**
     * Sets the value of the cloudstable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setCloudstable(ListTableType value) {
        this.cloudstable = value;
    }

    /**
     * Gets the value of the seatable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getSeatable() {
        return seatable;
    }

    /**
     * Sets the value of the seatable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setSeatable(ListTableType value) {
        this.seatable = value;
    }

    /**
     * Gets the value of the weathertable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getWeathertable() {
        return weathertable;
    }

    /**
     * Sets the value of the weathertable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setWeathertable(ListTableType value) {
        this.weathertable = value;
    }

    /**
     * Gets the value of the taxatable property.
     * 
     * @return
     *     possible object is
     *     {@link TaxaTableType }
     *     
     */
    public TaxaTableType getTaxatable() {
        return taxatable;
    }

    /**
     * Sets the value of the taxatable property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxaTableType }
     *     
     */
    public void setTaxatable(TaxaTableType value) {
        this.taxatable = value;
    }

    /**
     * Gets the value of the identificationtable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getIdentificationtable() {
        return identificationtable;
    }

    /**
     * Sets the value of the identificationtable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setIdentificationtable(ListTableType value) {
        this.identificationtable = value;
    }

    /**
     * Gets the value of the sampletypetable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getSampletypetable() {
        return sampletypetable;
    }

    /**
     * Sets the value of the sampletypetable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setSampletypetable(ListTableType value) {
        this.sampletypetable = value;
    }

    /**
     * Gets the value of the grouptable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getGrouptable() {
        return grouptable;
    }

    /**
     * Sets the value of the grouptable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setGrouptable(ListTableType value) {
        this.grouptable = value;
    }

    /**
     * Gets the value of the conservationtable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getConservationtable() {
        return conservationtable;
    }

    /**
     * Sets the value of the conservationtable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setConservationtable(ListTableType value) {
        this.conservationtable = value;
    }

    /**
     * Gets the value of the producttypetable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getProducttypetable() {
        return producttypetable;
    }

    /**
     * Sets the value of the producttypetable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setProducttypetable(ListTableType value) {
        this.producttypetable = value;
    }

    /**
     * Gets the value of the abundancecategorytable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getAbundancecategorytable() {
        return abundancecategorytable;
    }

    /**
     * Sets the value of the abundancecategorytable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setAbundancecategorytable(ListTableType value) {
        this.abundancecategorytable = value;
    }

    /**
     * Gets the value of the lengthmeasurementtable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getLengthmeasurementtable() {
        return lengthmeasurementtable;
    }

    /**
     * Sets the value of the lengthmeasurementtable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setLengthmeasurementtable(ListTableType value) {
        this.lengthmeasurementtable = value;
    }

    /**
     * Gets the value of the agingstructuretable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getAgingstructuretable() {
        return agingstructuretable;
    }

    /**
     * Sets the value of the agingstructuretable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setAgingstructuretable(ListTableType value) {
        this.agingstructuretable = value;
    }

    /**
     * Gets the value of the parasitetable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getParasitetable() {
        return parasitetable;
    }

    /**
     * Sets the value of the parasitetable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setParasitetable(ListTableType value) {
        this.parasitetable = value;
    }

    /**
     * Gets the value of the stomachtable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getStomachtable() {
        return stomachtable;
    }

    /**
     * Sets the value of the stomachtable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setStomachtable(ListTableType value) {
        this.stomachtable = value;
    }

    /**
     * Gets the value of the intestinetable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getIntestinetable() {
        return intestinetable;
    }

    /**
     * Sets the value of the intestinetable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setIntestinetable(ListTableType value) {
        this.intestinetable = value;
    }

    /**
     * Gets the value of the tissuesampletable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getTissuesampletable() {
        return tissuesampletable;
    }

    /**
     * Sets the value of the tissuesampletable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setTissuesampletable(ListTableType value) {
        this.tissuesampletable = value;
    }

    /**
     * Gets the value of the samplerecipienttable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getSamplerecipienttable() {
        return samplerecipienttable;
    }

    /**
     * Sets the value of the samplerecipienttable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setSamplerecipienttable(ListTableType value) {
        this.samplerecipienttable = value;
    }

    /**
     * Gets the value of the foreignobjecttable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getForeignobjecttable() {
        return foreignobjecttable;
    }

    /**
     * Sets the value of the foreignobjecttable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setForeignobjecttable(ListTableType value) {
        this.foreignobjecttable = value;
    }

    /**
     * Gets the value of the lengthresolutiontable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getLengthresolutiontable() {
        return lengthresolutiontable;
    }

    /**
     * Sets the value of the lengthresolutiontable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setLengthresolutiontable(ListTableType value) {
        this.lengthresolutiontable = value;
    }

    /**
     * Gets the value of the fattable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getFattable() {
        return fattable;
    }

    /**
     * Sets the value of the fattable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setFattable(ListTableType value) {
        this.fattable = value;
    }

    /**
     * Gets the value of the sextable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getSextable() {
        return sextable;
    }

    /**
     * Sets the value of the sextable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setSextable(ListTableType value) {
        this.sextable = value;
    }

    /**
     * Gets the value of the maturationstagetable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getMaturationstagetable() {
        return maturationstagetable;
    }

    /**
     * Sets the value of the maturationstagetable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setMaturationstagetable(ListTableType value) {
        this.maturationstagetable = value;
    }

    /**
     * Gets the value of the stomachfilltable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getStomachfilltable() {
        return stomachfilltable;
    }

    /**
     * Sets the value of the stomachfilltable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setStomachfilltable(ListTableType value) {
        this.stomachfilltable = value;
    }

    /**
     * Gets the value of the digestiontable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getDigestiontable() {
        return digestiontable;
    }

    /**
     * Sets the value of the digestiontable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setDigestiontable(ListTableType value) {
        this.digestiontable = value;
    }

    /**
     * Gets the value of the livertable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getLivertable() {
        return livertable;
    }

    /**
     * Sets the value of the livertable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setLivertable(ListTableType value) {
        this.livertable = value;
    }

    /**
     * Gets the value of the liverparasitetable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getLiverparasitetable() {
        return liverparasitetable;
    }

    /**
     * Sets the value of the liverparasitetable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setLiverparasitetable(ListTableType value) {
        this.liverparasitetable = value;
    }

    /**
     * Gets the value of the gillwormstable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getGillwormstable() {
        return gillwormstable;
    }

    /**
     * Sets the value of the gillwormstable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setGillwormstable(ListTableType value) {
        this.gillwormstable = value;
    }

    /**
     * Gets the value of the swollengillstable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getSwollengillstable() {
        return swollengillstable;
    }

    /**
     * Sets the value of the swollengillstable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setSwollengillstable(ListTableType value) {
        this.swollengillstable = value;
    }

    /**
     * Gets the value of the fungushearttable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getFungushearttable() {
        return fungushearttable;
    }

    /**
     * Sets the value of the fungushearttable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setFungushearttable(ListTableType value) {
        this.fungushearttable = value;
    }

    /**
     * Gets the value of the fungussporestable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getFungussporestable() {
        return fungussporestable;
    }

    /**
     * Sets the value of the fungussporestable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setFungussporestable(ListTableType value) {
        this.fungussporestable = value;
    }

    /**
     * Gets the value of the fungusoutertable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getFungusoutertable() {
        return fungusoutertable;
    }

    /**
     * Sets the value of the fungusoutertable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setFungusoutertable(ListTableType value) {
        this.fungusoutertable = value;
    }

    /**
     * Gets the value of the blackspottable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getBlackspottable() {
        return blackspottable;
    }

    /**
     * Sets the value of the blackspottable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setBlackspottable(ListTableType value) {
        this.blackspottable = value;
    }

    /**
     * Gets the value of the readabilitytable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getReadabilitytable() {
        return readabilitytable;
    }

    /**
     * Sets the value of the readabilitytable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setReadabilitytable(ListTableType value) {
        this.readabilitytable = value;
    }

    /**
     * Gets the value of the otolithedgetable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getOtolithedgetable() {
        return otolithedgetable;
    }

    /**
     * Sets the value of the otolithedgetable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setOtolithedgetable(ListTableType value) {
        this.otolithedgetable = value;
    }

    /**
     * Gets the value of the otolithcentretable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getOtolithcentretable() {
        return otolithcentretable;
    }

    /**
     * Sets the value of the otolithcentretable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setOtolithcentretable(ListTableType value) {
        this.otolithcentretable = value;
    }

    /**
     * Gets the value of the blindreadingtable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getBlindreadingtable() {
        return blindreadingtable;
    }

    /**
     * Sets the value of the blindreadingtable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setBlindreadingtable(ListTableType value) {
        this.blindreadingtable = value;
    }

    /**
     * Gets the value of the agereadertable property.
     * 
     * @return
     *     possible object is
     *     {@link AgereaderTableType }
     *     
     */
    public AgereaderTableType getAgereadertable() {
        return agereadertable;
    }

    /**
     * Sets the value of the agereadertable property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgereaderTableType }
     *     
     */
    public void setAgereadertable(AgereaderTableType value) {
        this.agereadertable = value;
    }

    /**
     * Gets the value of the tagtypetable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getTagtypetable() {
        return tagtypetable;
    }

    /**
     * Sets the value of the tagtypetable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setTagtypetable(ListTableType value) {
        this.tagtypetable = value;
    }

    /**
     * Gets the value of the preysourcetable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getPreysourcetable() {
        return preysourcetable;
    }

    /**
     * Sets the value of the preysourcetable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setPreysourcetable(ListTableType value) {
        this.preysourcetable = value;
    }

    /**
     * Gets the value of the weightresolutiontable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getWeightresolutiontable() {
        return weightresolutiontable;
    }

    /**
     * Sets the value of the weightresolutiontable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setWeightresolutiontable(ListTableType value) {
        this.weightresolutiontable = value;
    }

    /**
     * Gets the value of the devstagetable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getDevstagetable() {
        return devstagetable;
    }

    /**
     * Sets the value of the devstagetable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setDevstagetable(ListTableType value) {
        this.devstagetable = value;
    }

    /**
     * Gets the value of the copepodedevstagetable property.
     * 
     * @return
     *     possible object is
     *     {@link ListTableType }
     *     
     */
    public ListTableType getCopepodedevstagetable() {
        return copepodedevstagetable;
    }

    /**
     * Sets the value of the copepodedevstagetable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListTableType }
     *     
     */
    public void setCopepodedevstagetable(ListTableType value) {
        this.copepodedevstagetable = value;
    }

}
