//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 02:52:48 PM CEST 
//


package BioticTypes.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._2001.xmlschema.Adapter1;


/**
 * <p>Java class for TagType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TagType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tagtype" type="{http://www.imr.no/formats/nmdbiotic/v3}KeyType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="tagid" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TagType", propOrder = {
    "tagtype"
})
public class TagType {

    protected String tagtype;
    @XmlAttribute(name = "tagid", required = true)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Integer tagid;

    /**
     * Gets the value of the tagtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTagtype() {
        return tagtype;
    }

    /**
     * Sets the value of the tagtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTagtype(String value) {
        this.tagtype = value;
    }

    /**
     * Gets the value of the tagid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getTagid() {
        return tagid;
    }

    /**
     * Sets the value of the tagid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTagid(Integer value) {
        this.tagid = value;
    }

}
